import { getUserByCookies } from "@/utils";

const userData = getUserByCookies();

const fieldData = {
  igmGenerationFields: [
    {
      label: "Vessel",
      name: "vessel",
      type: "dropdown",
      tableName: "tblVessel t",
      idColumn: "id",
      displayColumn: "t.name",
      changeFun: "handleChangeOnVessel",
      searchColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "Voyage",
      name: "voyage",
      type: "dropdown",
      tableName: "tblVoyage t",
      idColumn: "id",
      displayColumn: "t.voyageNo",
      searchColumn: "t.voyageNo",
      selectedConditions: [{ vessel: "vesselId" }],
      where: `t.status = 1 and t.companyid = ${userData?.companyId}`,
      orderBy: "t.voyageNo",
      isEdit: true,
    },
    {
      label: "POD",
      name: "pod",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      changeFun: "handleDropdownChange",
      joins: `join tblMasterData d on p.portTypeId = d.id and d.name = 'SEA PORT' join tblVoyageRoute v on v.portOfCallId = p.id`,
      selectedConditions: [{ voyage: "v.voyageId" }],
      searchColumn: "p.name",
      orderBy: "p.name",
      isEdit: true,
    },
    {
      label: "BL No",
      name: "blNo",
      isEdit: true,
    },
    {
      label: "Container No",
      name: "containerNo",
      isEdit: true,
    },
    {
      label: "FPD",
      name: "fpd",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "CFS",
      name: "cfs",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      joins: `join tblMasterData m on m.id = p.portTypeId  and m.masterListName = 'tblPortType' and m.code = 'CFS' and p.companyId = ${userData?.companyId}`,
      selectedConditions: [{ pod: "p.referencePortId" }],
      isEdit: true,
    },
    // {
    //   label: "ICD",
    //   name: "icd",
    //   type: "dropdown",
    //   tableName: "tblPort p",
    //   displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
    //   joins: `join tblMasterData m on m.id = p.portTypeId  and m.masterListName = 'tblPortType' and m.code = 'ICD'`,
    //   isEdit: true,
    // },
    {
      label: "DPD",
      name: "dpd",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      joins: `join tblMasterData m on m.id = p.portTypeId  and m.masterListName = 'tblPortType' and m.code = 'DPD' and p.companyId = ${userData?.companyId}`,
      isEdit: true,
    },
    {
      label: "Empty Yard",
      name: "emptyYard",
      type: "dropdown",
      tableName: "tblPort t",
      displayColumn: "ISNULL(t.code,'') + ' - ' + ISNULL(t.name,'')",
      joins: "JOIN tblMasterData m ON m.id = t.portTypeId",
      where: "m.masterListName = 'tblPortType' AND m.code = 'D'",
      orderBy: "t.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "From Date",
      name: "fromDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "To Date ",
      name: "toDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "Location",
      name: "locationId",
      type: "multiselectCheckBox",
      tableName: "tblLocation l",
      displayColumn: "l.name",
      foreignTable: "name,tblLocation",
      orderBy: "l.name",
      where: `id in (${userData?.locations})`,
      isEdit: true,
    },
    {
      label: "Select Report ",
      name: "selReportId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'doRegisterName'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
  ],
};
export default fieldData;
export const metaData = [];
