import { getUserByCookies } from "@/utils";
const userData = getUserByCookies();
const fieldData = {
  igmGenerationFields: [
    {
      label: "Liner",
      name: "shippingLineId",
      type: "dropdown",
      tableName: "tblCompany c",
      idColumn: "id",
      displayColumn: "c.name",
      searchColumn: "c.name",
      orderBy: "c.name",
      isEdit: true,
    },
    {
      label: "Vessel",
      name: "vessel",
      type: "dropdown",
      tableName: "tblVessel t",
      idColumn: "id",
      displayColumn: "t.name",
      searchColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
      changeFun: "handleDropdownChange", // 👈 change this
    },
    {
      label: "Voyage",
      name: "voyage",
      type: "dropdown",
      tableName: "tblVoyage t",
      idColumn: "id",
      changeFun: "handleDropdownChange",
      displayColumn: "t.voyageNo",
      searchColumn: "t.voyageNo",
      selectedConditions: [
        { vessel: "vesselId" },
        { shippingLineId: "companyid" },
      ],
      where: `t.status = 1`,
      orderBy: "t.voyageNo",
      isEdit: true,
    },
    {
      label: "POD",
      name: "pod",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      changeFun: "handleDropdownChange",
      joins: `join tblMasterData d on p.portTypeId = d.id and d.name = 'SEA PORT' join tblVoyageRoute v on v.portOfCallId = p.id`,
      selectedConditions: [{ voyage: "v.voyageId" }],
      searchColumn: "p.name",
      orderBy: "p.name",
      isEdit: true,
      changeFun: "handleDropdownChange",
    },
    {
      label: "Status",
      name: "status",
      type: "dropdown",
      isEdit: false,
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "masterListName = 'tblCfsStatusType'",
      foreignTable: "name,tblMasterData",
      isEdit: true,
      orderBy: "m.name",
      isEdit: true,
    },
    {
      label: "From Date",
      name: "fromDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "To Date ",
      name: "toDate",
      type: "date",
      isEdit: true,
    },
  ],
};
export default fieldData;
export const metaData = [];
