const fieldData = {
  igmEdiFields: [
    {
      label: "Vessel",
      name: "vessel",
      type: "dropdown",
      tableName: "tblVessel t",
      idColumn: "id",
      changeFun: "handleChangeOnVessel",
      displayColumn: "t.name",
      searchColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "Voyage",
      name: "voyage",
      type: "dropdown",
      tableName: "tblVoyage t",
      changeFun: "handleDropdownChange",
      idColumn: "id",
      displayColumn: "t.voyageNo",
      selectedConditions: [{ vessel: "vesselId" }],
      searchColumn: "t.voyageNo",
      orderBy: "t.voyageNo",
      isEdit: true,
    },
    {
      label: "POD",
      name: "pod",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      changeFun: "handleDropdownChange",
      joins: `join tblMasterData d on p.portTypeId = d.id and d.name = 'SEA PORT' join tblVoyageRoute v on v.portOfCallId = p.id`,
      selectedConditions: [{ voyage: "v.voyageId" }],
      searchColumn: "p.name",
      orderBy: "p.name",
      isEdit: true,
    },
    {
      label: "Terminal",
      name: "terminal",
      type: "dropdown",
      tableName: "tblPort p",
      idColumn: "id",
      displayColumn: "p.name",
      joins: `join tblMasterData d on p.portTypeId = d.id and d.name = 'PORT TERMINAL'`,
      selectedConditions: [{ pod: "p.referencePortId" }],
      searchColumn: "p.name",
      orderBy: "p.name",
      isEdit: true,
    },
  ],
};

export default fieldData;
export const metaData = [];
