import AddIcon from "@mui/icons-material/Add";
import CloseIcon from "@mui/icons-material/Close";
const fieldData = {
  igmFields: [
    {
      label: "Liner Name",
      name: "LinerName",
      type: "dropdown",
      tableName: "tblCompany t",
      idColumn: "id",
      displayColumn: "t.name",
      searchColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
      required: true,
    },
    {
      label: "BL NO",
      name: "blNo",
      required: true,
      isEdit: true,
    },

    // {
    //   label: "Type",
    //   name: "type",
    //   type: "dropdown",
    //   tableName: "tblMasterData m",
    //   idColumn: "id",
    //   displayColumn: "m.name",
    //   searchColumn: "m.name",
    //   orderBy: "m.name",
    //   where: "m.masterListName = 'tblServiceType'",
    //   isEdit: true,
    //   required: true,
    // },
    {
      label: "BL Location",
      name: "blLocation",
      type: "dropdown",
      tableName: "tblPort p",
      idColumn: "id",
      displayColumn: "p.name",
      searchColumn: "p.name",
      orderBy: "p.name",
      isEdit: true,
      required: true,
    },
    {
      label: "Type Of Delivery ",
      name: "typeOfDelivery",
      type: "dropdown",
      tableName: "tblMasterData m",
      idColumn: "id",
      displayColumn: "m.name",
      searchColumn: "m.name",
      orderBy: "m.name",
      where: "m.masterListName = 'tblStuffingDestuffingType'",
      isEdit: true,
      required: true,
    },
    {
      label: "Free Days",
      name: "freeDays",
      isEdit: true,
      type: "checkbox",
    },
    {
      label: " Valid Till",
      name: "validTill",
      type: "date",
      isEdit: true,
    },
    {
      label: "Do Extension",
      name: "doExtension",
      isEdit: true,
      type: "checkbox",
    },
    {
      label: "High Sea Sales",
      name: "HighSeaSales",
      isEdit: true,
      type: "checkbox",
    },
    {
      label: " Port Storage Date",
      name: "PortStorageDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "Remarks",
      name: "remarks",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
    },
  ],
  invoiceFields: [
    {
      label: "Name",
      name: "name",
      isEdit: true,
    },
    {
      label: "GSTIN/Provisional ID",
      name: "gstin",
      isEdit: true,
    },
    {
      label: "Address",
      name: "address",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
    },
    {
      label: "Contact",
      name: "contact",
      type: "number",
      isEdit: true,
    },
    {
      label: "Email",
      name: "name",
      isEdit: true,
    },
  ],
  attachmentFields: [
    {
      label: "Select",
      name: "select",
      type: "dropdown",
      tableName: "tblMasterData m",
      idColumn: "id",
      displayColumn: "m.name",
      searchColumn: "m.name",
      orderBy: "m.name",
      where: "m.masterListName = 'tblDocument'",
      isEdit: true,
    },
    {
      label: "Upload",
      name: "upload",
      type: "fileupload",
      isEdit: true,
    },
    {
      label: "Remarks",
      name: "remark",
      isEdit: true,
    },
  ],
  containerFields: [
    {
      label: "Container No",
      name: "containerNo",
      isEdit: true,
    },
    {
      label: "Container Size",
      name: "ContainerSize",
      type: "dropdown",
      tableName: "tblMasterData m",
      idColumn: "id",
      displayColumn: "m.name",
      searchColumn: "m.name",
      orderBy: "m.name",
      where: "m.masterListName = 'tblSize'",
      isEdit: true,
    },
    {
      label: " Valid Till",
      name: "validTill",
      type: "date",
      isEdit: true,
    },
  ],
};

export default fieldData;
export const cfsGridButtons = [
  {
    text: "Add ",
    icon: <AddIcon />,
    func: "gridAddHandler",
  },
  {
    text: "Delete ",
    icon: <CloseIcon />,
    func: "gridDeleteHandler",
  },
];
