export const navItems = [
  { name: "Home", href: "/" },
  {
    name: "Master",
    submenu: [
      { name: "Commodity", href: "/master/commodity/list" },
      { name: "Company", href: "/master/company/list" },
      { name: "Company Branch", href: "/master/companyBranch/list" },
      { name: "Container Size", href: "/master/containerSize/list" },
      { name: "Container Status", href: "/master/containerStatus/list" },
      { name: "Container Type", href: "/master/containerType/list" },
      { name: "CFS", href: "/master/cfs/list" },
      { name: "Depot", href: "/master/depot/list" },
      { name: "ISO Code", href: "/master/isoCode/list" },
      { name: "IMO ", href: "/master/imo/list" },
      { name: "ITEM Type", href: "/master/itemType/list" },
      { name: "Cargo Type", href: "/master/cargoType/list" },
      { name: "Country", href: "/master/country/list" },
      { name: "Vessel", href: "/master/vessel/list" },
      { name: "Voyage Route", href: "/master/voyageRoute/list" },
      { name: "City", href: "/master/city/list" },
      { name: "State", href: "/master/state/list" },
      { name: "Port", href: "/master/port/list" },
      { name: "Nominated Area", href: "/master/nominatedArea/list" },
      { name: "Terminal", href: "/master/terminal/list" },
      { name: "Dpd", href: "/master/dpd/list" },
      { name: "Type Of Company", href: "/master/typeOfCompany/list" },
      { name: "Package Type", href: "/master/packageType/list" },
      { name: "Voyage", href: "/master/voyage/list" },
      { name: "User", href: "/master/user/list" },
      { name: "Unit", href: "/master/unit/list" },
      { name: "Unit Type", href: "/master/unitType/list" },
      { name: "SMTP", href: "/master/smtpCarrier/list" },
      { name: "Mode Of Transport", href: "/master/modeOfTransport/list" },
      { name: "Movement Type", href: "/master/movementType/list" },
    ],
  },
  {
    name: "BL",
    href: "/bl/list",
  },
  { name: "HBL", href: "/hbl/list" },
];
