const fieldData = {
    slabWiseReportFields: [
        {
            label: "Vessel",
            name: "vesselId",
            type: "dropdown",
            tableName: "tblVessel t",
            idColumn: "id",
            displayColumn: "t.name",
            searchColumn: "t.name",
            orderBy: "t.name",
            isEdit: true,
        },
        {
            label: "Voyage",
            name: "voyageId",
            type: "dropdown",
            tableName: "tblVoyage t",
            idColumn: "id",
            displayColumn: "t.voyageNo",
            searchColumn: "t.voyageNo",
            selectedConditions: [{ vessel: "vesselId" }],
            orderBy: "t.voyageNo",
            isEdit: true,
        },
        {
            label: "BL No",
            name: "blNo",
            isEdit: true,
        },
        {
            label: "Container No",
            name: "containerNo",
            isEdit: true,
        },
        {
            label: "POD",
            name: "podId",
            type: "dropdown",
            tableName: "tblPort p",
            displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
            orderBy: "p.name",
            foreignTable: "code-name,tblPort",
            isEdit: true,
        },
        {
            label: "FPD",
            name: "fpdId",
            type: "dropdown",
            tableName: "tblPort p",
            displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
            orderBy: "p.name",
            foreignTable: "code-name,tblPort",
            isEdit: true,
        },
        {
            label: "CFS",
            name: "cfsId",
            type: "dropdown",
            tableName: "tblPort p",
            displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
            joins: "LEFT JOIN tblMasterData m ON m.id = p.portTypeId",
            searchColumn: "p.name",
            where: "m.masterListName = 'tblPortType' AND m.code = 'CFS'",
            orderBy: "p.name",
            foreignTable: "code-name,tblPort",
            isEdit: true,
        },
        {
            label: "ICD",
            name: "icdId",
            type: "dropdown",
            tableName: "tblPort t",
            displayColumn: "ISNULL(t.code,'') + ' - ' + ISNULL(t.name,'')",
            joins: "JOIN tblMasterData m ON m.id = t.portTypeId",
            where: "m.masterListName = 'tblPortType' AND m.code = 'ICD'",
            orderBy: "t.name",
            foreignTable: "code-name,tblPort",
            isEdit: true,
        },
        {
            label: "DPD",
            name: "dpdId",
            type: "dropdown",
            tableName: "tblPort t",
            displayColumn: "ISNULL(t.code,'') + ' - ' + ISNULL(t.name,'')",
            joins: "JOIN tblMasterData m ON m.id = t.portTypeId",
            where: "m.masterListName = 'tblPortType' AND m.code = 'DPD'",
            orderBy: "t.name",
            foreignTable: "code-name,tblPort",
            isEdit: true,
        },
        {
            label: "Empty Yard",
            name: "emptyYardId",
            type: "dropdown",
            tableName: "tblPort t",
            displayColumn: "ISNULL(t.code,'') + ' - ' + ISNULL(t.name,'')",
            joins: "JOIN tblMasterData m ON m.id = t.portTypeId",
            where: "m.masterListName = 'tblPortType' AND m.code = 'D'",
            orderBy: "t.name",
            foreignTable: "code-name,tblPort",
            isEdit: true,
        },
        {
            label: "From Date",
            name: "fromDate",
            type: "date",
            isEdit: true,
        },
        {
            label: "To Date ",
            name: "toDate",
            type: "date",
            isEdit: true,
        },
        {
            label: "Select Report ",
            name: "",
            type: "",
            isEdit: true,
        },
    ],
};
export default fieldData;
export const metaData = [];
