const fieldData = {
  auditFields: [
    // {
    //   label: "Location",
    //   name: "pod",
    //   type: "dropdown",
    //   tableName: "tblPort p",
    //   displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
    //   joins: `join tblMasterData d on p.portTypeId = d.id and d.name = 'SEA PORT' `,
    //   orderBy: "p.name",
    //   foreignTable: "code-name,tblPort",
    //   isEdit: true,
    // },
    {
      label: "Vessel",
      name: "vesselId",
      type: "dropdown",
      tableName: "tblVessel t",
      idColumn: "id",
      displayColumn: "t.name",
      searchColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "Voyage",
      name: "voyageId",
      type: "dropdown",
      tableName: "tblVoyage t",
      idColumn: "id",
      displayColumn: "t.voyageNo",
      searchColumn: "t.voyageNo",
      selectedConditions: [{ vesselId: "vesselId" }],
      orderBy: "t.voyageNo",
      isEdit: true,
    },
    {
      label: "POD",
      name: "podId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      joins: `join tblMasterData d on p.portTypeId = d.id and d.name = 'SEA PORT' join tblVoyageRoute v on v.portOfCallId = p.id`,
      selectedConditions: [{ voyageId: "v.voyageId" }],
      searchColumn: "p.name",
      orderBy: "p.name",
      isEdit: true,
    },
    {
      label: "BL No",
      name: "blNo",
      isEdit: true,
    },
  ],
};
export default fieldData;
export const metaData = [];
