import AddIcon from "@mui/icons-material/Add";
import CloseIcon from "@mui/icons-material/Close";
import FileCopyIcon from "@mui/icons-material/FileCopy";
import UploadFileIcon from "@mui/icons-material/UploadFile";
import { layouts } from "chart.js";

export const fieldData = {
  doRequestFields: [
    {
      label: "Liner",
      name: "shippingLineId",
      type: "dropdown",
      tableName: "tblCompany t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCompany",
      required: true,
      isEdit: true,
    },
    {
      label: "BL No",
      name: "blNo",
      required: true,
      blurFun: "fetchInvoicePaymentByBlAndLiner",
    },
    {
      label: "Cargo Type",
      name: "cargoTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblCargoType'",
      foreignTable: "name,tblMasterData",
      orderBy: "m.name",
      isEdit: true,
      required: true,
    },
    {
      label: "DE StuFfing Type",
      name: "stuffDestuffId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where:
        "m.masterListName = 'tblStuffingDestuffingType' and m.name <> 'Factory' and m.name <> 'Dock'",
      foreignTable: "name,tblMasterData",
      orderBy: "m.name",
      isEdit: true,
    },
    {
      name: "isFreeDays",
      type: "radio",
      radioData: [
        { label: "Free Days", value: "Y" },
        { label: "Do Extension", value: "N" },
      ],
      isEdit: true,
      changeFun: "freeDaysChangeHandler",
    },
    {
      label: "Remarks",
      name: "doRemarks",
      type: "textarea",
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
    },
    {
      label: "Mobile No",
      name: "doRequestTelNo",
      isEdit: true,
    },
    {
      label: "HSS Customer Name",
      name: "newConsigneeText",
      isEdit: true,
    },
    {
      label: "Factory Address",
      name: "deliveryAddress",
      type: "textarea",
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
    },
    {
      label: "Factory Location Pin",
      name: "deliveryZipCode",
      isEdit: true,
    },
    {
      label: "Custom Broker",
      name: "customBrokerText",
      isEdit: true,
    },
    {
      label: "Empty Yard",
      name: "emptyDepotId",
      type: "dropdown",
      displayColumn: "p.name",
      tableName: "tblPort p",
      joins: `join tblMasterData m on m.id = p.portTypeId and m.name = 'DEPOT' and p.status = 1`,
      orderBy: "p.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
      disabled: true,
    },
    {
      label: "Surveyor",
      name: "surveyorText",
      isEdit: true,
      disabled: true,
    },
    {
      label: "Nominated Area (CFS)",
      name: "nominatedAreaId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      joins: `join tblMasterData m on m.id = p.portTypeId  and m.masterListName = 'tblPortType' and m.code = 'CFS'`,
      searchColumn: "p.name",
      selectedConditions: [{ shippingLineId: "companyId" }],
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      style: "col-span-2 row-span-1",
      isEdit: true,
    },
  ],

  tblInvoicePayment: [
    {
      label: "Payment Type",
      name: "paymentTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      where: "m.masterListName = 'tblPaymentType' AND m.name <> 'Receipt'",
      displayColumn: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
    {
      label: "Amount",
      name: "Amount",
      type: "number",
      isEdit: true,
    },
    {
      label: "Bank Name",
      name: "bankName",
      type: "text",
      isEdit: true,
    },
    {
      label: "Branch Name",
      name: "bankBranchName",
      type: "text",
      isEdit: true,
    },
    {
      label: "Instrument Number",
      name: "referenceNo",
      type: "text",
      isEdit: true,
    },
    {
      label: "Instrument Date",
      name: "referenceDate",
      type: "date",
      isEdit: true,
    },
    // {
    //   label: "Invoice No",
    //   // name: "invoiceIds",
    //   type: "text",
    //   isEdit: true,
    //   disabled: true,
    //   // foreignTable: "invoiceNo,tblInvoice",
    // },
    {
      label: "Status",
      name: "paymentStatusId",
      type: "dropdown",
      tableName: "tblMasterData m",
      where: "m.masterListName = 'tblPaymentStatus'",
      displayColumn: "m.name",
      foreignTable: "name,tblMasterData",
    },
  ],

  tblBlContainer: [
    {
      label: "Select For DO",
      name: "selectForDO",
      type: "checkbox",
      isEdit: true,
    },
    {
      label: "CONTAINER NO",
      name: "containerNo",
      isEdit: true,
      required: true,
      disabled: true,
    },
    {
      label: "Size",
      name: "sizeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblSize'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
      changeFun: "setISOBySize",
      disabled: true,
    },
    {
      label: "Type",
      name: "typeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblType'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      isEdit: true,
      changeFun: "setISOByType",
      disabled: true,
    },
    {
      label: " Valid Till",
      name: "doValidityDate",
      type: "date",
      isEdit: true,
    },
  ],

  tblAttachment: [
    {
      label: "Select",
      name: "attachmentTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      idColumn: "id",
      displayColumn: "m.name",
      searchColumn: "m.name",
      orderBy: "m.name",
      where:
        "m.masterListName = 'tblInvoiceAttachmentType' and m.name <> 'DO Released' and m.name <> 'Empty Letter'",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
    {
      label: "Upload",
      name: "path",
      type: "fileupload",
      isEdit: true,
      required: true,
    },
    {
      label: "Remarks",
      name: "remarks",
      isEdit: true,
    },
  ],

  tblAttachmentRelease: [
    {
      label: "Select",
      name: "attachmentTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      idColumn: "id",
      displayColumn: "m.name",
      searchColumn: "m.name",
      orderBy: "m.name",
      where:
        "m.masterListName = 'tblInvoiceAttachmentType' and m.name = 'DO Released' or m.name = 'Empty Letter'",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
    {
      label: "Upload",
      name: "path",
      type: "fileupload",
      isEdit: true,
      required: true,
    },
    {
      label: "Remarks",
      name: "remarks",
      isEdit: true,
    },
  ],
};
export const cfsGridButtons = [
  { text: "Add", icon: <AddIcon />, func: "gridAddHandler" },
  { text: "Delete", icon: <CloseIcon />, func: "gridDeleteHandler" },
];

export const advanceSearchFields = {
  bl: [
    {
      label: "Liner",
      name: "shippingLineId",
      type: "multiselect",
      tableName: "tblCompany t",
      displayColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "BL No",
      name: "blNo",
      isEdit: true,
    },
    {
      label: "Status",
      name: "doRequestStatusId",
      type: "multiselect",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblDoStatus'",
      orderBy: "m.name",
      isEdit: true,
    },
  ],
  shipBl: [
    {
      label: "BL No",
      name: "blNo",
      isEdit: true,
    },
    {
      label: "Status",
      name: "doRequestStatusId",
      type: "multiselect",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblDoStatus'",
      orderBy: "m.name",
      isEdit: true,
    },
  ],
};
