const fieldData = {
    cargoFields: [
        {
            label: "Vessel",
            name: "vessel",
            type: "dropdown",
            tableName: "tblVessel t",
            idColumn: "id",
            displayColumn: "t.name",
            searchColumn: "t.name",
            changeFun: "handleChangeOnVessel",
            orderBy: "t.name",
            isEdit: true,
        },
        {
            label: "Voyage",
            name: "voyage",
            type: "dropdown",
            tableName: "tblVoyage t",
            changeFun: "handleDropdownChange",
            idColumn: "id",
            displayColumn: "t.voyageNo",
            selectedConditions: [{ vessel: "vesselId" }],
            searchColumn: "t.voyageNo",
            orderBy: "t.voyageNo",
            isEdit: true,
        },
        {
            label: "POD",
            name: "pod",
            type: "dropdown",
            tableName: "tblPort p",
            displayColumn: "p.name",
            changeFun: "handleDropdownChange",
            joins: `join tblMasterData d on p.portTypeId = d.id and d.name = 'SEA PORT' join tblVoyageRoute v on v.portOfCallId = p.id`,
            selectedConditions: [{ voyage: "v.voyageId" }],
            searchColumn: "p.name",
            orderBy: "p.name",
            isEdit: true,
        },
        {
            label: "FPD",
            name: "terminal",
            type: "dropdown",
            tableName: "tblPort t",
            idColumn: "id",
            displayColumn: "t.name",
            searchColumn: "t.name",
            orderBy: "t.name",
            isEdit: true,
        },
    ],
};
export default fieldData;
export const metaData = [];
