export const SmapleMenuData = {
  data: [
    {
      id: 891,
      menuName: "Admin",
      parentMenuId: null,
      menuLink: null,
      menuOrder: 1,
      isFormcontrol: false,
      icon: null,
      menuType: "F",
      formControlId: null,
      reportId: null,
      status: true,
      deletedNo: 891,
      clientId: 1,
      createdDate: "2024-12-21T13:21:15.850",
      createdBy: 4,
      updatedDate: null,
      updatedBy: null,
      child: [
        {
          id: 1087,
          menuName: "Themes",
          parentMenuId: 891,
          menuLink: "/default",
          menuOrder: 15,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1254,
          menuName: "Reports Theme",
          parentMenuId: 891,
          menuLink: "/default",
          menuOrder: 16,
          isFormcontrol: null,
          icon: null,
          menuType: "F",
          formControlId: "1777",
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2025-04-16T11:22:18.100",
          createdBy: 36,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 971,
          menuName: "Create Menu",
          parentMenuId: 891,
          menuLink: "/default",
          menuOrder: 101,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 971,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1147,
          menuName: "Menu Form Mapping",
          parentMenuId: 891,
          menuLink: "/default",
          menuOrder: 102,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1147,
          clientId: 1,
          createdDate: "2025-01-07T15:45:15.047",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1262,
          menuName: "Create Dynamic Report",
          parentMenuId: 891,
          menuLink: "/default",
          menuOrder: 102,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2024-04-29T13:21:00",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: [
            {
              id: 1274,
              menuName: "Menu Report Mapping",
              parentMenuId: 1262,
              menuLink: "/default",
              menuOrder: 10,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: null,
              clientId: 1,
              createdDate: "2025-04-29T15:24:00",
              createdBy: 94,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1070,
              menuName: "API Fields",
              parentMenuId: 1262,
              menuLink: "/default",
              menuOrder: 11,
              isFormcontrol: true,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: null,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1263,
              menuName: "Create Report Criteria",
              parentMenuId: 1262,
              menuLink: "/default",
              menuOrder: 102,
              isFormcontrol: true,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: null,
              clientId: 1,
              createdDate: "2024-04-29T13:21:00",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1264,
              menuName: "Create Button Criteria",
              parentMenuId: 1262,
              menuLink: "/default",
              menuOrder: 102,
              isFormcontrol: true,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: null,
              clientId: 1,
              createdDate: "2024-04-29T13:21:00",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
          ],
        },
        {
          id: 895,
          menuName: "Create Form Control",
          parentMenuId: 891,
          menuLink: "/createFormControl",
          menuOrder: 103,
          isFormcontrol: true,
          icon: null,
          menuType: "S",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 895,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 897,
          menuName: "Create Excel Upload",
          parentMenuId: 891,
          menuLink: null,
          menuOrder: 104,
          isFormcontrol: null,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 897,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1009,
          menuName: "Create Dashboard",
          parentMenuId: 891,
          menuLink: "/CreateDashboard",
          menuOrder: 105,
          isFormcontrol: true,
          icon: null,
          menuType: "S",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1009,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1179,
          menuName: "Upload Logo",
          parentMenuId: 891,
          menuLink: "/uploadLogo",
          menuOrder: 106,
          isFormcontrol: null,
          icon: null,
          menuType: "S",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2025-03-05T12:15:11.160",
          createdBy: 36,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1181,
          menuName: "Upload Header/Footer",
          parentMenuId: 891,
          menuLink: "/uploadHeaderAndFooter",
          menuOrder: 107,
          isFormcontrol: null,
          icon: null,
          menuType: "S",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2025-03-07T11:02:56.210",
          createdBy: 36,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 973,
          menuName: "Report Search Criteria",
          parentMenuId: 891,
          menuLink: "/default",
          menuOrder: 108,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 973,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1011,
          menuName: "Copy Table Mapping",
          parentMenuId: 891,
          menuLink: "/default",
          menuOrder: 109,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1011,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 894,
          menuName: "Access Control",
          parentMenuId: 891,
          menuLink: null,
          menuOrder: 111,
          isFormcontrol: null,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 894,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: [
            {
              id: 1336,
              menuName: "Menu Access",
              parentMenuId: 894,
              menuLink: "/menuAccess",
              menuOrder: 15,
              isFormcontrol: false,
              icon: null,
              menuType: "S",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: null,
              clientId: 1,
              createdDate: "2024-12-21T13:21:00",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 893,
              menuName: "Roles",
              parentMenuId: 894,
              menuLink: null,
              menuOrder: 1001,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 893,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 892,
              menuName: "User",
              parentMenuId: 894,
              menuLink: null,
              menuOrder: 1002,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 892,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
          ],
        },
        {
          id: 1154,
          menuName: "Business Segment",
          parentMenuId: 891,
          menuLink: "/default",
          menuOrder: 119,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1154,
          clientId: 1,
          createdDate: "2025-01-29T19:12:42.370",
          createdBy: 37,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
      ],
    },
    {
      id: 898,
      menuName: "Masters",
      parentMenuId: null,
      menuLink: null,
      menuOrder: 2,
      isFormcontrol: false,
      icon: null,
      menuType: "F",
      formControlId: null,
      reportId: null,
      status: true,
      deletedNo: 898,
      clientId: 1,
      createdDate: "2024-12-21T13:21:15.850",
      createdBy: 4,
      updatedDate: null,
      updatedBy: null,
      child: [
        {
          id: 899,
          menuName: "Accounts",
          parentMenuId: 898,
          menuLink: null,
          menuOrder: 112,
          isFormcontrol: false,
          icon: null,
          menuType: null,
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 899,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: [
            {
              id: 1097,
              menuName: "Trial Balance Group",
              parentMenuId: 899,
              menuLink: "/default",
              menuOrder: 1003,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1097,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 902,
              menuName: "Party Ledger",
              parentMenuId: 899,
              menuLink: null,
              menuOrder: 1004,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 902,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 901,
              menuName: "General Ledger",
              parentMenuId: 899,
              menuLink: null,
              menuOrder: 1005,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 901,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 903,
              menuName: "Tax",
              parentMenuId: 899,
              menuLink: null,
              menuOrder: 1006,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 903,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 906,
              menuName: "SAC",
              parentMenuId: 899,
              menuLink: null,
              menuOrder: 1007,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 906,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1098,
              menuName: "Tax Category",
              parentMenuId: 899,
              menuLink: "/default",
              menuOrder: 1008,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1098,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1186,
              menuName: "HSN",
              parentMenuId: 899,
              menuLink: "/default",
              menuOrder: 1009,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: null,
              clientId: 1,
              createdDate: "2025-03-15T16:35:13.650",
              createdBy: 95,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1187,
              menuName: "TDS",
              parentMenuId: 899,
              menuLink: "/default",
              menuOrder: 1010,
              isFormcontrol: true,
              icon: null,
              menuType: "F",
              formControlId: "1723",
              reportId: null,
              status: true,
              deletedNo: null,
              clientId: 1,
              createdDate: "2025-03-15T16:36:17.340",
              createdBy: 95,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1188,
              menuName: "Party TDS Mapping",
              parentMenuId: 899,
              menuLink: "/default",
              menuOrder: 1011,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: null,
              clientId: 1,
              createdDate: "2025-03-15T16:41:00.077",
              createdBy: 95,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
          ],
        },
        {
          id: 908,
          menuName: "Charge",
          parentMenuId: 898,
          menuLink: null,
          menuOrder: 113,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 908,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: [
            {
              id: 909,
              menuName: "Charge Group",
              parentMenuId: 908,
              menuLink: null,
              menuOrder: 1112,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 909,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 910,
              menuName: "Charge",
              parentMenuId: 908,
              menuLink: null,
              menuOrder: 1113,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 910,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1095,
              menuName: "RateBasis",
              parentMenuId: 908,
              menuLink: "/default",
              menuOrder: 1114,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1095,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
          ],
        },
        {
          id: 913,
          menuName: "Commodity",
          parentMenuId: 898,
          menuLink: null,
          menuOrder: 114,
          isFormcontrol: false,
          icon: null,
          menuType: null,
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 913,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: [
            {
              id: 1075,
              menuName: "Cargo Type",
              parentMenuId: 913,
              menuLink: "/default",
              menuOrder: 1115,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1075,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1076,
              menuName: "Unit Type",
              parentMenuId: 913,
              menuLink: "/default",
              menuOrder: 1116,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1076,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 915,
              menuName: "Unit",
              parentMenuId: 913,
              menuLink: null,
              menuOrder: 1117,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 915,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 914,
              menuName: "Package",
              parentMenuId: 913,
              menuLink: null,
              menuOrder: 1118,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 914,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 917,
              menuName: "Commodity Type",
              parentMenuId: 913,
              menuLink: null,
              menuOrder: 1119,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 917,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1059,
              menuName: "Commodity Status",
              parentMenuId: 913,
              menuLink: "/default",
              menuOrder: 1120,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1059,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1058,
              menuName: "Storage Type",
              parentMenuId: 913,
              menuLink: "/default",
              menuOrder: 1121,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1058,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1057,
              menuName: "Warehouse Type",
              parentMenuId: 913,
              menuLink: "/default",
              menuOrder: 1122,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1057,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1021,
              menuName: "Product",
              parentMenuId: 913,
              menuLink: null,
              menuOrder: 1123,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1021,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
          ],
        },
        {
          id: 929,
          menuName: "Location",
          parentMenuId: 898,
          menuLink: null,
          menuOrder: 115,
          isFormcontrol: null,
          icon: null,
          menuType: null,
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 929,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: [
            {
              id: 930,
              menuName: "Country",
              parentMenuId: 929,
              menuLink: null,
              menuOrder: 1124,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 930,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 932,
              menuName: "Port",
              parentMenuId: 929,
              menuLink: null,
              menuOrder: 1125,
              isFormcontrol: null,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 932,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
          ],
        },
        {
          id: 933,
          menuName: "Vessel Voyage",
          parentMenuId: 898,
          menuLink: null,
          menuOrder: 116,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 933,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: [
            {
              id: 1152,
              menuName: "Vessel Voyage",
              parentMenuId: 933,
              menuLink: null,
              menuOrder: 1129,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1152,
              clientId: 1,
              createdDate: "2024-12-21T13:21:00",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1173,
              menuName: "Vessel Schedule",
              parentMenuId: 933,
              menuLink: "/default",
              menuOrder: 1130,
              isFormcontrol: true,
              icon: null,
              menuType: "F",
              formControlId: "1648",
              reportId: null,
              status: true,
              deletedNo: 1173,
              clientId: 1,
              createdDate: "2025-02-25T18:43:34.733",
              createdBy: 46,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
          ],
        },
        {
          id: 1110,
          menuName: "Transportations",
          parentMenuId: 898,
          menuLink: "/default",
          menuOrder: 117,
          isFormcontrol: false,
          icon: null,
          menuType: null,
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1110,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: [
            {
              id: 1111,
              menuName: "Vehicle Type",
              parentMenuId: 1110,
              menuLink: "/default",
              menuOrder: 1131,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1111,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1112,
              menuName: "Maintenance Type",
              parentMenuId: 1110,
              menuLink: "/default",
              menuOrder: 1132,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1112,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1119,
              menuName: "Fuel Type",
              parentMenuId: 1110,
              menuLink: "/default",
              menuOrder: 1133,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1119,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1114,
              menuName: "Order Type",
              parentMenuId: 1110,
              menuLink: "/default",
              menuOrder: 1134,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1114,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1115,
              menuName: "Service Type",
              parentMenuId: 1110,
              menuLink: "/default",
              menuOrder: 1135,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1115,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1116,
              menuName: "Order Status",
              parentMenuId: 1110,
              menuLink: "/default",
              menuOrder: 1136,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1116,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1118,
              menuName: "Incident Status",
              parentMenuId: 1110,
              menuLink: "/default",
              menuOrder: 1137,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1118,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1117,
              menuName: "Gender",
              parentMenuId: 1110,
              menuLink: "/default",
              menuOrder: 1138,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1117,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1102,
              menuName: "Vehicle",
              parentMenuId: 1110,
              menuLink: "/default",
              menuOrder: 1139,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1102,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
          ],
        },
        {
          id: 1153,
          menuName: "CRM",
          parentMenuId: 898,
          menuLink: "/default",
          menuOrder: 118,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1153,
          clientId: 1,
          createdDate: "2025-01-29T19:02:46.497",
          createdBy: 37,
          updatedDate: null,
          updatedBy: null,
          child: [
            {
              id: 1160,
              menuName: "Company Subtype",
              parentMenuId: 1153,
              menuLink: "/default",
              menuOrder: 120,
              isFormcontrol: true,
              icon: null,
              menuType: "F",
              formControlId: "1606",
              reportId: null,
              status: true,
              deletedNo: 1160,
              clientId: 1,
              createdDate: "2025-01-30T18:01:48.193",
              createdBy: 43,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1161,
              menuName: "Company",
              parentMenuId: 1153,
              menuLink: "/default",
              menuOrder: 121,
              isFormcontrol: true,
              icon: null,
              menuType: "F",
              formControlId: "1615",
              reportId: null,
              status: true,
              deletedNo: 1161,
              clientId: 1,
              createdDate: "2025-02-01T11:59:49.990",
              createdBy: 43,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
          ],
        },
        {
          id: 1162,
          menuName: "Terms and Conditions",
          parentMenuId: 898,
          menuLink: "/default",
          menuOrder: 122,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1162,
          clientId: 1,
          createdDate: "2025-02-01T13:55:05.663",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
      ],
    },
    {
      id: 940,
      menuName: "Quotation",
      parentMenuId: null,
      menuLink: null,
      menuOrder: 3,
      isFormcontrol: false,
      icon: null,
      menuType: "F",
      formControlId: null,
      reportId: null,
      status: true,
      deletedNo: 940,
      clientId: 1,
      createdDate: "2024-12-21T13:21:15.850",
      createdBy: 4,
      updatedDate: null,
      updatedBy: null,
      child: [
        {
          id: 1163,
          menuName: "Export Sea",
          parentMenuId: 940,
          menuLink: "/default",
          menuOrder: 123,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1163,
          clientId: 1,
          createdDate: "2024-12-21T13:21:00",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1174,
          menuName: "Export Air",
          parentMenuId: 940,
          menuLink: "/default",
          menuOrder: 124,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: "1647",
          reportId: null,
          status: true,
          deletedNo: 1174,
          clientId: 1,
          createdDate: "2025-02-26T10:43:11.283",
          createdBy: 52,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1144,
          menuName: "Transportation Buy Tariff",
          parentMenuId: 940,
          menuLink: "/default",
          menuOrder: 125,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1144,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1128,
          menuName: "Transportation",
          parentMenuId: 940,
          menuLink: "/default",
          menuOrder: 126,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1128,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1093,
          menuName: "Warehouse",
          parentMenuId: 940,
          menuLink: "/default",
          menuOrder: 127,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1093,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
      ],
    },
    {
      id: 1171,
      menuName: "Job",
      parentMenuId: null,
      menuLink: "/default",
      menuOrder: 4,
      isFormcontrol: true,
      icon: null,
      menuType: "F",
      formControlId: null,
      reportId: null,
      status: true,
      deletedNo: 1171,
      clientId: 1,
      createdDate: "2025-02-20T17:26:00",
      createdBy: 52,
      updatedDate: null,
      updatedBy: null,
      child: [
        {
          id: 1170,
          menuName: "Export FF Sea",
          parentMenuId: 1171,
          menuLink: "/default",
          menuOrder: 1,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: "1642",
          reportId: null,
          status: true,
          deletedNo: 1170,
          clientId: 1,
          createdDate: "2025-02-21T12:31:00",
          createdBy: 94,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1259,
          menuName: "Master Job",
          parentMenuId: 1171,
          menuLink: "/default",
          menuOrder: 1,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: "1780",
          reportId: null,
          status: true,
          deletedNo: 1170,
          clientId: 1,
          createdDate: "2025-02-21T12:31:00",
          createdBy: 94,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1260,
          menuName: "Sub Job",
          parentMenuId: 1171,
          menuLink: "/default",
          menuOrder: 1,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: "1781",
          reportId: null,
          status: true,
          deletedNo: 1170,
          clientId: 1,
          createdDate: "2025-02-21T12:31:00",
          createdBy: 94,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1278,
          menuName: "Export Agency Job",
          parentMenuId: 1171,
          menuLink: "/default",
          menuOrder: 1,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: "1793",
          reportId: null,
          status: true,
          deletedNo: 1170,
          clientId: 1,
          createdDate: "2025-02-21T12:31:00",
          createdBy: 94,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1279,
          menuName: "Import Agency Job",
          parentMenuId: 1171,
          menuLink: "/default",
          menuOrder: 1,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: "1794",
          reportId: null,
          status: true,
          deletedNo: 1170,
          clientId: 1,
          createdDate: "2025-02-21T12:31:00",
          createdBy: 94,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1341,
          menuName: "Cross Trade Sea",
          parentMenuId: 1171,
          menuLink: "/default",
          menuOrder: 1,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: "1642",
          reportId: null,
          status: true,
          deletedNo: 1170,
          clientId: 1,
          createdDate: "2025-02-21T12:31:00",
          createdBy: 94,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1169,
          menuName: "Export FF Air",
          parentMenuId: 1171,
          menuLink: "/default",
          menuOrder: 3,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: "1637",
          reportId: null,
          status: true,
          deletedNo: 1169,
          clientId: 1,
          createdDate: "2025-02-22T16:14:04.093",
          createdBy: 94,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1342,
          menuName: "Cross Trade Air",
          parentMenuId: 1171,
          menuLink: "/default",
          menuOrder: 3,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: "1637",
          reportId: null,
          status: true,
          deletedNo: 1169,
          clientId: 1,
          createdDate: "2025-02-22T16:14:00",
          createdBy: 94,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
      ],
    },
    {
      id: 919,
      menuName: "WareHouse",
      parentMenuId: null,
      menuLink: null,
      menuOrder: 6,
      isFormcontrol: null,
      icon: null,
      menuType: "F",
      formControlId: null,
      reportId: null,
      status: true,
      deletedNo: 919,
      clientId: 1,
      createdDate: "2024-12-21T13:21:15.850",
      createdBy: 4,
      updatedDate: null,
      updatedBy: null,
      child: [
        {
          id: 1013,
          menuName: "Purchase Order",
          parentMenuId: 919,
          menuLink: "/default",
          menuOrder: 141,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1013,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 884,
          menuName: "Goods Inward",
          parentMenuId: 919,
          menuLink: "/default",
          menuOrder: 142,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 884,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 889,
          menuName: "Sales Order",
          parentMenuId: 919,
          menuLink: "/default",
          menuOrder: 143,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 889,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 890,
          menuName: "Goods Outward",
          parentMenuId: 919,
          menuLink: "/default",
          menuOrder: 144,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 890,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 969,
          menuName: "Goods Delivery",
          parentMenuId: 919,
          menuLink: null,
          menuOrder: 145,
          isFormcontrol: null,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 969,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
      ],
    },
    {
      id: 1101,
      menuName: "Transportation",
      parentMenuId: null,
      menuLink: "/default",
      menuOrder: 7,
      isFormcontrol: false,
      icon: null,
      menuType: "F",
      formControlId: null,
      reportId: null,
      status: true,
      deletedNo: 1101,
      clientId: 1,
      createdDate: "2024-12-21T13:21:15.850",
      createdBy: 4,
      updatedDate: null,
      updatedBy: null,
      child: [
        {
          id: 1108,
          menuName: "Transport Job",
          parentMenuId: 1101,
          menuLink: "/default",
          menuOrder: 141,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1108,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1109,
          menuName: "Vehicle Planning",
          parentMenuId: 1101,
          menuLink: "/default",
          menuOrder: 142,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: "1628",
          reportId: null,
          status: true,
          deletedNo: 1109,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 43,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1104,
          menuName: "Vehicle Insurance",
          parentMenuId: 1101,
          menuLink: "/default",
          menuOrder: 143,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1104,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1105,
          menuName: "Vehicle Maintenance",
          parentMenuId: 1101,
          menuLink: "/default",
          menuOrder: 144,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1105,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1106,
          menuName: "Vehicle Incident",
          parentMenuId: 1101,
          menuLink: "/default",
          menuOrder: 145,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1106,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1107,
          menuName: "Vehicle Fuel Log",
          parentMenuId: 1101,
          menuLink: "/default",
          menuOrder: 146,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1107,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
      ],
    },
    {
      id: 952,
      menuName: "Invoice",
      parentMenuId: null,
      menuLink: "/invoiceControl",
      menuOrder: 8,
      isFormcontrol: true,
      icon: null,
      menuType: "F",
      formControlId: null,
      reportId: null,
      status: true,
      deletedNo: 952,
      clientId: 1,
      createdDate: "2024-12-21T13:21:15.850",
      createdBy: 4,
      updatedDate: null,
      updatedBy: null,
      child: [
        {
          id: 1198,
          menuName: "Export Air",
          parentMenuId: 952,
          menuLink: "/invoiceControl",
          menuOrder: 3,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2025-03-15T00:00:00",
          createdBy: 94,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1197,
          menuName: "Export Sea ",
          parentMenuId: 952,
          menuLink: "/invoiceControl",
          menuOrder: 155,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2025-03-15T00:00:00",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1096,
          menuName: "Warehouse",
          parentMenuId: 952,
          menuLink: "/invoiceControl",
          menuOrder: 157,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1096,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1125,
          menuName: "Transportation",
          parentMenuId: 952,
          menuLink: "/invoiceControl",
          menuOrder: 158,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1125,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1234,
          menuName: "Sales",
          parentMenuId: 952,
          menuLink: "/invoiceControl",
          menuOrder: 160,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1096,
          clientId: 1,
          createdDate: "2024-12-21T13:21:00",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: [
            {
              id: 1232,
              menuName: "Sales Invoice",
              parentMenuId: 1234,
              menuLink: "/invoiceControl",
              menuOrder: 158,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1096,
              clientId: 1,
              createdDate: "2024-12-21T13:21:00",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1246,
              menuName: "Proforma Invoice",
              parentMenuId: 1234,
              menuLink: "/invoiceControl",
              menuOrder: 158,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1096,
              clientId: 1,
              createdDate: "2024-12-21T13:21:00",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1250,
              menuName: "Credit Note",
              parentMenuId: 1234,
              menuLink: "/invoiceControl",
              menuOrder: 158,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1096,
              clientId: 1,
              createdDate: "2024-12-21T13:21:00",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1276,
              menuName: "Export Agency Invoice",
              parentMenuId: 1234,
              menuLink: "/invoiceControl",
              menuOrder: 158,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1096,
              clientId: 1,
              createdDate: "2024-12-21T13:21:00",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1277,
              menuName: "Import Agency Invoice",
              parentMenuId: 1234,
              menuLink: "/invoiceControl",
              menuOrder: 158,
              isFormcontrol: false,
              icon: null,
              menuType: "F",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1096,
              clientId: 1,
              createdDate: "2024-12-21T13:21:00",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
          ],
        },
      ],
    },
    {
      id: 958,
      menuName: "Voucher",
      parentMenuId: null,
      menuLink: null,
      menuOrder: 8,
      isFormcontrol: true,
      icon: null,
      menuType: "F",
      formControlId: null,
      reportId: null,
      status: true,
      deletedNo: null,
      clientId: 1,
      createdDate: "2024-12-21T13:21:15.850",
      createdBy: 4,
      updatedDate: null,
      updatedBy: null,
      child: [
        {
          id: 960,
          menuName: "Bank Receipt",
          parentMenuId: 958,
          menuLink: "/voucher/bankReceipt",
          menuOrder: 1,
          isFormcontrol: true,
          icon: null,
          menuType: "S",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 959,
          menuName: "Bank Payment",
          parentMenuId: 958,
          menuLink: "/voucher/bankPayment",
          menuOrder: 2,
          isFormcontrol: true,
          icon: null,
          menuType: "S",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 961,
          menuName: "Cash Receipt",
          parentMenuId: 958,
          menuLink: "/invoiceControl",
          menuOrder: 3,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 962,
          menuName: "Cash Payment",
          parentMenuId: 958,
          menuLink: "/invoiceControl",
          menuOrder: 4,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1005,
          menuName: "Journal Voucher",
          parentMenuId: 958,
          menuLink: "/invoiceControl",
          menuOrder: 5,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 963,
          menuName: "Contra Voucher",
          parentMenuId: 958,
          menuLink: "/invoiceControl",
          menuOrder: 6,
          isFormcontrol: true,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1375,
          menuName: "Bank Receipt New",
          parentMenuId: 958,
          menuLink: "/voucherControl",
          menuOrder: 158,
          isFormcontrol: false,
          icon: null,
          menuType: "F",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1096,
          clientId: 1,
          createdDate: "2024-12-21T13:21:00",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
      ],
    },
    {
      id: 880,
      menuName: "Reports",
      parentMenuId: null,
      menuLink: "/dynamicReports",
      menuOrder: 11,
      isFormcontrol: false,
      icon: null,
      menuType: "R",
      formControlId: null,
      reportId: null,
      status: true,
      deletedNo: 880,
      clientId: 1,
      createdDate: "2024-12-21T13:21:15.850",
      createdBy: 4,
      updatedDate: null,
      updatedBy: null,
      child: [
        {
          id: 882,
          menuName: "Operational",
          parentMenuId: 880,
          menuLink: null,
          menuOrder: 1,
          isFormcontrol: false,
          icon: null,
          menuType: "R",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 882,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: [
            {
              id: 979,
              menuName: "Quotation Report",
              parentMenuId: 882,
              menuLink: "/dynamicReports",
              menuOrder: 1,
              isFormcontrol: false,
              icon: null,
              menuType: "D",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: null,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1245,
              menuName: "Job",
              parentMenuId: 882,
              menuLink: "/dynamicReports",
              menuOrder: 2,
              isFormcontrol: true,
              icon: null,
              menuType: "D",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: null,
              clientId: 1,
              createdDate: "2024-12-21T13:21:00",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
          ],
        },
        {
          id: 881,
          menuName: "Accounts",
          parentMenuId: 880,
          menuLink: null,
          menuOrder: 2,
          isFormcontrol: false,
          icon: null,
          menuType: "R",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 881,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: [
            {
              id: 992,
              menuName: "Books of Accounts",
              parentMenuId: 881,
              menuLink: "/default",
              menuOrder: 6,
              isFormcontrol: true,
              icon: null,
              menuType: "R",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 992,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: [
                {
                  id: 900,
                  menuName: "Trial Balance",
                  parentMenuId: 992,
                  menuLink: "/accountingReports/trialBalance",
                  menuOrder: 1,
                  isFormcontrol: false,
                  icon: null,
                  menuType: "S",
                  formControlId: null,
                  reportId: null,
                  status: true,
                  deletedNo: 900,
                  clientId: 1,
                  createdDate: "2024-12-21T13:21:15.850",
                  createdBy: 4,
                  updatedDate: null,
                  updatedBy: null,
                  child: null,
                },
              ],
            },
            {
              id: 1235,
              menuName: "Invoice",
              parentMenuId: 881,
              menuLink: "/dynamicReports",
              menuOrder: 6,
              isFormcontrol: true,
              icon: null,
              menuType: "D",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 992,
              clientId: 1,
              createdDate: "2024-12-21T13:21:00",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: [
                {
                  id: 1243,
                  menuName: "Purchase Register",
                  parentMenuId: 1235,
                  menuLink: "/dynamicReports",
                  menuOrder: 1,
                  isFormcontrol: true,
                  icon: null,
                  menuType: "D",
                  formControlId: null,
                  reportId: null,
                  status: true,
                  deletedNo: null,
                  clientId: 1,
                  createdDate: "2024-12-21T13:21:00",
                  createdBy: 4,
                  updatedDate: null,
                  updatedBy: null,
                  child: null,
                },
                {
                  id: 1244,
                  menuName: "Invoice Register Chargewise Rowwise",
                  parentMenuId: 1235,
                  menuLink: "/dynamicReports",
                  menuOrder: 2,
                  isFormcontrol: true,
                  icon: null,
                  menuType: "D",
                  formControlId: null,
                  reportId: null,
                  status: true,
                  deletedNo: null,
                  clientId: 1,
                  createdDate: "2024-12-21T13:21:00",
                  createdBy: 4,
                  updatedDate: null,
                  updatedBy: null,
                  child: null,
                },
                {
                  id: 1236,
                  menuName: "Invoice Register",
                  parentMenuId: 1235,
                  menuLink: "/dynamicReports",
                  menuOrder: 6,
                  isFormcontrol: true,
                  icon: null,
                  menuType: "D",
                  formControlId: null,
                  reportId: null,
                  status: true,
                  deletedNo: 992,
                  clientId: 1,
                  createdDate: "2024-12-21T13:21:00",
                  createdBy: 4,
                  updatedDate: null,
                  updatedBy: null,
                  child: null,
                },
              ],
            },
          ],
        },
        {
          id: 1072,
          menuName: "Warehouse Reports",
          parentMenuId: 880,
          menuLink: "/default",
          menuOrder: 3,
          isFormcontrol: true,
          icon: null,
          menuType: "D",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1072,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: [
            {
              id: 1073,
              menuName: "Warehouse Stock Report",
              parentMenuId: 1072,
              menuLink: "/dynamicReports",
              menuOrder: 1,
              isFormcontrol: true,
              icon: null,
              menuType: "D",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1073,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1077,
              menuName: "Purchase Order Report",
              parentMenuId: 1072,
              menuLink: "/dynamicReports",
              menuOrder: 2,
              isFormcontrol: true,
              icon: null,
              menuType: "D",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1077,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1078,
              menuName: "Goods Inward Register",
              parentMenuId: 1072,
              menuLink: "/dynamicReports",
              menuOrder: 3,
              isFormcontrol: true,
              icon: null,
              menuType: "D",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1078,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1079,
              menuName: "Goods Receipt Register",
              parentMenuId: 1072,
              menuLink: "/dynamicReports",
              menuOrder: 4,
              isFormcontrol: true,
              icon: null,
              menuType: "D",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1079,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1080,
              menuName: "Stock Detailed Report",
              parentMenuId: 1072,
              menuLink: "/dynamicReports",
              menuOrder: 5,
              isFormcontrol: true,
              icon: null,
              menuType: "D",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1080,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1081,
              menuName: "Sales Order Report",
              parentMenuId: 1072,
              menuLink: "/dynamicReports",
              menuOrder: 6,
              isFormcontrol: true,
              icon: null,
              menuType: "D",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1081,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1082,
              menuName: "Goods Outward Register",
              parentMenuId: 1072,
              menuLink: "/dynamicReports",
              menuOrder: 7,
              isFormcontrol: true,
              icon: null,
              menuType: "D",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1082,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1083,
              menuName: "Goods Delivery Register",
              parentMenuId: 1072,
              menuLink: "/dynamicReports",
              menuOrder: 8,
              isFormcontrol: true,
              icon: null,
              menuType: "D",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1083,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
            {
              id: 1086,
              menuName: "Warehouse Report",
              parentMenuId: 1072,
              menuLink: "/dynamicReports",
              menuOrder: 9,
              isFormcontrol: true,
              icon: null,
              menuType: "D",
              formControlId: null,
              reportId: null,
              status: true,
              deletedNo: 1086,
              clientId: 1,
              createdDate: "2024-12-21T13:21:15.850",
              createdBy: 4,
              updatedDate: null,
              updatedBy: null,
              child: null,
            },
          ],
        },
        {
          id: 1130,
          menuName: "Container Planning",
          parentMenuId: 880,
          menuLink: "/dynamicReports",
          menuOrder: 33,
          isFormcontrol: true,
          icon: null,
          menuType: "D",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1130,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1184,
          menuName: "Country Data Chart",
          parentMenuId: 880,
          menuLink: "/dynamicReports",
          menuOrder: 33,
          isFormcontrol: true,
          icon: null,
          menuType: "C",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2025-03-10T15:29:27.537",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1229,
          menuName: "New Country Data Chart",
          parentMenuId: 880,
          menuLink: "/dynamicReports",
          menuOrder: 33,
          isFormcontrol: true,
          icon: null,
          menuType: "C",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2025-03-21T11:11:20.277",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1256,
          menuName: "Company Quotation",
          parentMenuId: 880,
          menuLink: "/dynamicReports",
          menuOrder: 33,
          isFormcontrol: true,
          icon: null,
          menuType: "C",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: null,
          clientId: 1,
          createdDate: "2025-04-23T12:03:31.467",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
        {
          id: 1140,
          menuName: "Transportation Job Report",
          parentMenuId: 880,
          menuLink: "/dynamicReports",
          menuOrder: 35,
          isFormcontrol: true,
          icon: null,
          menuType: "D",
          formControlId: null,
          reportId: null,
          status: true,
          deletedNo: 1140,
          clientId: 1,
          createdDate: "2024-12-21T13:21:15.850",
          createdBy: 4,
          updatedDate: null,
          updatedBy: null,
          child: null,
        },
      ],
    },
  ],
};
