const fieldData = {
  mblFields: [
    {
      label: "Location(POD)",
      name: "department",
      type: "dropdown",
      labelType: "port",
      required: true,
    },
    {
      label: "Liner/FF",
      name: "liner",
      type: "dropdown",
      labelType: "port",
      required: true,
    },
    {
      label: "MBL No",
      name: "mblNo",
      required: true,
    },
    {
      label: "MBL Date",
      name: "bookingReferenceNo",
      type: "date",
      required: true,
    },
    {
      label: "Vessel-Voyage No.",
      name: "vesselVoyageNo",
      type: "dropdown",
      labelType: "vessel",
      required: true,
    },
    {
      label: "Manifest Vessel-Voyage",
      name: "manifestVessel",
      type: "dropdown",
      labelType: "vessel",
    },
    {
      label: "Type of Cargo",
      name: "typeOfCargo",
      type: "dropdown",
      labelType: "name,tblCargoType",
      foreignTable: "name,tblMasterData",
    },
    {
      label: "Port of Acceptance",
      name: "portOfAcceptance",
    },
    {
      label: "Port of Loading",
      name: "portOfLoading",
      type: "dropdown",
      labelType: "port",
      required: true,
    },
    {
      label: "Port of Unloading",
      name: "portOfUnloading",
      type: "dropdown",
      labelType: "port",
      required: true,
    },
    {
      label: "Port of Destination",
      name: "portOfDestination",
      type: "dropdown",
      labelType: "port",
    },
    {
      label: "CIN Type",
      name: "cinType",
      type: "dropdown",
      labelType: "port",
    },
    {
      label: "CIN No",
      name: "cinNo",
    },
    {
      label: "Container Status",
      name: "containerStatus",
      type: "dropdown",
      labelType: "name,tblContainerStatus",
      foreignTable: "name,tblMasterData",
      required: true,
    },
    {
      label: "Mobile(Requester)",
      name: "mobileNo",
      type: "number",
      required: true,
    },
    {
      label: "Voyage Number",
      name: "voyageNumber",
      type: "number",
    },
    {
      label: "Liner/FF Pan",
      name: "linerFFPan",
      type: "dropdown",
      labelType: "port",
    },
    {
      label: "IGM No",
      name: "igmNo",
      required: true,
    },
    {
      label: "IGM Date",
      name: "igmDate",
      type: "date",
      required: true,
    },
    {
      label: "Status",
      name: "status",
      type: "dropdown",
      labelType: "container",
      required: true,
    },
    {
      label: "Rejection Remarks",
      name: "rejectRemarks",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      required: true,
    },
  ],
  csnFields: [
    {
      label: "Sender Id",
      name: "senderId",
    },
    {
      label: "Receive Id",
      name: "receiveId",
    },
    {
      label: "Vessel Id Type",
      name: "vesselIdType",
      type: "dropdown",
      labelType: "vessel",
      required: true,
    },
    {
      label: "Vessel No",
      name: "vesselNo",
    },
    {
      label: "Submit Type",
      name: "submitType",
      type: "dropdown",
      labelType: "vessel",
    },
    {
      label: "Code",
      name: "code",
    },
    {
      label: "VCN No",
      name: "vcnNo",
    },
    {
      label: "CSN No",
      name: "csnNo",
    },
    {
      label: "CSN Date",
      name: "csnDate",
    },
  ],
  hblFields: [
    {
      label: "HBL No",
      name: "hblNo",
      required: true,
    },
    {
      label: "HBL Date",
      name: "hblDate",
      type: "date",
      required: true,
    },
    {
      label: "CIN Type",
      name: "cinType",
      type: "dropdown",
      labelType: "port",
    },
    {
      label: "CIN NO",
      name: "cinNo",
    },
    {
      label: "CSN No",
      name: "csnNo",
    },
    {
      label: "CSN Date",
      name: "csnDate",
      type: "date",
    },
    {
      label: "Item Type",
      name: "itemType",
      type: "dropdown",
      labelType: "name,tblItemType",
      foreignTable: "name,tblMasterData",
      required: true,
    },
    {
      label: "Nature of Cargo",
      name: "natureOfCargo",
      type: "dropdown",
      labelType: "port",
      style: "col-span-2 row-span-1",
      required: true,
    },
    {
      label: "Short Shipment",
      name: "shortShipment",
      type: "checkbox",
    },
    {
      label: "FF Pan",
      name: "ffPan",
      type: "dropdown",
      labelType: "port",
      required: true,
    },
  ],
  hblBottomFields: [
    {
      label: "Marks & Numbers",
      name: "marksAndNumbers",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      required: true,
    },
    {
      label: "Good & Description",
      name: "goodAndDescription",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      required: true,
    },
    {
      label: "Invoice Value",
      name: "invoiceValue",
    },
    {
      label: "Currency",
      name: "currencyId",
      type: "dropdown",
      labelType: "code,tblCurrency",
      foreignTable: "name,tblMasterData",
    },
  ],
  transitFields: [
    { label: "Transit Bond No", name: "transitBondNo" },
    { label: "Carrier Code", name: "carrierCode" },
  ],
  consignorFields: [
    { label: "Name", name: "consignorName", required: true },
    { label: "Code", name: "consignorCode" },
    {
      label: "Type",
      name: "consignorType",
      type: "dropdown",
      labelType: "name,tblType",
      foreignTable: "name,tblMasterData",
    },
    {
      label: "Country",
      name: "consignorCountry",
      type: "dropdown",
      labelType: "country",
      required: true,
    },
    {
      label: "State",
      name: "consignorState",
      type: "dropdown",
      labelType: "state",
      required: true,
    },
    {
      label: "City",
      name: "city",
      type: "dropdown",
      labelType: "city",
      selectedCondition: "consignorCountry",
      foreignTable: "name,tblCity",
      required: true,
    },
    { label: "Post Code", name: "consignorPostCode" },
    {
      label: "Address",
      name: "consignorAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      required: true,
    },
  ],
  consigneeFields: [
    { label: "Name", name: "consigneeName", required: true },
    { label: "Code", name: "consigneeCode" },
    {
      label: "Type",
      name: "consigneeType",
      type: "dropdown",
      labelType: "name,tblType",
      foreignTable: "name,tblMasterData",
    },
    {
      label: "Country",
      name: "consigneeCountry",
      type: "dropdown",
      labelType: "country",
      required: true,
    },
    {
      label: "State",
      name: "consigneeState",
      type: "dropdown",
      labelType: "state",
      required: true,
    },
    {
      label: "City",
      name: "cityId",
      type: "dropdown",
      labelType: "city",
      selectedCondition: "consigneeCountry",
      foreignTable: "name,tblCity",
      required: true,
    },
    { label: "GSTIN", name: "consigneeGSTIN" },
    { label: "IEC", name: "consigneeIEC", required: true },
    { label: "Email Id", name: "consigneeEmailId", required: true },
    { label: "Post Code", name: "consigneePostCode" },
    {
      label: "Address",
      name: "consigneeAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      required: true,
    },
  ],
  notifyFields: [
    { label: "Name", name: "notifyFieldsName", required: true },
    { label: "Code", name: "notifyFieldsCode" },
    {
      label: "Type",
      name: "notifyFieldsType",
      type: "dropdown",
      labelType: "name,tblType",
      foreignTable: "name,tblMasterData",
    },
    {
      label: "Country",
      name: "notifyFieldsCountry",
      type: "dropdown",
      labelType: "country",
      required: true,
    },
    {
      label: "State",
      name: "notifyFieldsState",
      type: "dropdown",
      labelType: "state",
      required: true,
    },
    {
      label: "City",
      name: "cityNotify",
      type: "dropdown",
      labelType: "city",
      selectedCondition: "notifyFieldsCountry",
      foreignTable: "name,tblCity",
      required: true,
    },
    { label: "Post Code", name: "notifyFieldsPostCode" },
    {
      label: "Address",
      name: "notifyFieldsAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      required: true,
    },
  ],
  invoiceFields: [
    {
      label: "Invoicing Consignee Name",
      name: "invoiceName",
      style: "col-span-2 row-span-1",
    },
    {
      label: "GSTIN No",
      name: "invoiceGSTINNO",
      style: "col-span-2 row-span-1",
    },
    {
      label: "Address",
      name: "invoiceAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
    },
  ],
  itemFields: [
    { label: "HS No", name: "itemHsNo", isEdit: true },
    { label: "Cargo Item Description", name: "itemCargoItemDes", isEdit: true },
    { label: "UNO Code", name: "itemUnoCode", isEdit: true },
    {
      label: "IMDG Code",
      name: "itemImdgCode",
      type: "dropdown",
      labelType: "port",
      isEdit: true,
    },
    {
      label: "No of Packages",
      name: "itemNoOfPackages",
      type: "number",
      isEdit: true,
    },
    {
      label: "Package Type Required",
      name: "itemPackagesType",
      type: "dropdown",
      labelType: "name,tblPackage",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
  ],
  containerFields: [
    { label: "Container No", name: "container", isEdit: true },
    { label: "Seal Type", name: "sealType", isEdit: true },
    { label: "Seal No", name: "sealNo", isEdit: true },
    { label: "SOC Flag", name: "Flag", isEdit: true },
    { label: "Container Agent Code", name: "Agent", isEdit: true },
    { label: "ISO Code", name: "Code", isEdit: true },
    {
      label: "Cargo Gross Wt(Kgs)",
      name: "Cargo",
      type: "number",
      isEdit: true,
    },
    {
      label: "Cargo net Wt(Kgs)",
      name: "cargoNo",
      type: "number",
      isEdit: true,
    },
    { label: "Gross Weight", name: "Gross", type: "number", isEdit: true },
    { label: "Volume(CBM)", name: "Volume", isEdit: true },
    { label: "No of Packages", name: "Packages", type: "number", isEdit: true },
    {
      label: "Package Type",
      name: "PackageType",
      type: "dropdown",
      labelType: "name,tblPackage",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
  ],
  itineraryFields: [
    { label: "From Port/ICD/Sez/CFS", name: "itineraryFrom", isEdit: true },
    { label: "To Port/ICD/Sez/CFS", name: "itineraryTo", isEdit: true },
    {
      label: "Mode of transport",
      name: "itineraryMode",
      type: "dropdown",
      labelType: "name,tblTransportType",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
  ],
};

export default fieldData;
