import AddIcon from "@mui/icons-material/Add";
import CloseIcon from "@mui/icons-material/Close";
import FileCopyIcon from "@mui/icons-material/FileCopy";
import UploadFileIcon from "@mui/icons-material/UploadFile";

export const fieldData = {
  mblFields: [
    {
      label: "Liner",
      name: "shippingLineId",
      type: "dropdown",
      tableName: "tblCompany t",
      displayColumn: "t.name",
      searchColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCompany",
      isEdit: true,
      required: true,
    },
    {
      label: "Company",
      name: "companyId",
      type: "dropdown",
      tableName: "tblCompany t",
      displayColumn: "t.name",
      searchColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCompany",
      required: true,
      disabled: true,
    },
    {
      label: "Company Branch",
      name: "companyBranchId",
      type: "dropdown",
      tableName: "tblCompanyBranch t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCompanyBranch",
      selectedConditions: [{ companyId: "companyId" }],
      required: true,
      disabled: true,
    },
    {
      label: "MBL No",
      name: "mblNo",
      isEdit: true,
      required: true,
      blurFun: "getMblHandler",
    },
    {
      label: "MBL Date",
      name: "mblDate",
      type: "date",
      isEdit: true,
      required: true,
    },
    {
      label: "Vessel-Voyage No.",
      name: "podvesselId",
      type: "dropdown",
      tableName: "tblVessel v",
      displayColumn: "ISNULL(v.name,'') + ' - ' + ISNULL(vo.voyageNo,'')",
      joins: "left JOIN tblVoyage vo ON vo.vesselId = v.id",
      searchColumn: "v.name",
      orderBy: "v.name, vo.voyageNo",
      foreignTable: "name,tblVessel",
      isEdit: true,
      required: true,
    },
    {
      label: "Type of Cargo",
      name: "cargoTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      foreignTable: "code-name,tblMasterData",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblCargoType'",
      orderBy: "m.name",
      isEdit: true,
      changeFun: "cargoTypeHandler",
    },
    {
      label: "Port of Loading",
      name: "polId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      joins:
        "JOIN tblMasterData m ON m.id = p.portTypeId JOIN tblCountry c ON c.id = p.countryId",
      where: "m.name IN ('SEA PORT','INLAND PORT')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
      required: true,
    },
    {
      label: "Port of Acceptance",
      name: "plrId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      joins:
        "JOIN tblMasterData m ON m.id = p.portTypeId JOIN tblCountry c ON c.id = p.countryId",
      where: "m.name IN ('SEA PORT','INLAND PORT')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "Port of Unloading",
      name: "podId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      joins:
        "JOIN tblMasterData m ON m.id = p.portTypeId JOIN tblCountry c ON c.id = p.countryId",
      where: "m.name IN ('SEA PORT') and c.name = 'India'",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
      required: true,
    },
    {
      label: "Port of Destination",
      name: "fpdId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      joins:
        "JOIN tblMasterData m ON m.id = p.portTypeId JOIN tblCountry c ON c.id = p.countryId",
      where: "m.name IN ('INLAND PORT') and c.name = 'India'",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "Container Status",
      name: "containerStatusId",
      type: "dropdown",
      displayColumn: "m.name",
      searchColumn: "m.name",
      orderBy: "m.name",
      tableName: "tblMasterData m",
      foreignTable: "code-name,tblMasterData",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblContainerStatus'",
      isEdit: true,
    },
    // {
    //   label: "Mobile(Requester)",
    //   name: "mobileNo",
    //   type: "number",
    //   required: true,
    //   isEdit: true,
    // },
  ],
  // csnFields: [
  //   // {
  //   //   label: "Sender Id",
  //   //   name: "senderId",
  //   //   isEdit: true,
  //   //   required: true,
  //   // },
  //   // {
  //   //   label: "Receive Id",
  //   //   name: "receiverId",
  //   //   isEdit: true,
  //   //   required: true,
  //   // },
  //   // {
  //   //   label: "Vessel Id Type",
  //   //   name: "vesselIdType",
  //   //   type: "dropdown",
  //   //   labelType: "vessel",
  //   //   required: true,
  //   //   isEdit: true,
  //   // },
  //   // {
  //   //   label: "Vessel No",
  //   //   name: "vesselNo",
  //   //   isEdit: true,
  //   //   required: true,
  //   // },
  //   // {
  //   //   label: "Submit Type",
  //   //   name: "submitterTypeId",
  //   //   type: "dropdown",
  //   //   labelType: "name,tblSubmitterType",
  //   //   foreignTable: "code-name,tblMasterData",
  //   //   isEdit: true,
  //   //   required: true,
  //   // },
  //   // {
  //   //   label: "Code",
  //   //   name: "code",
  //   //   isEdit: true,
  //   //   required: true,
  //   // },
  //   // {
  //   //   label: "Auth.Person Code",
  //   //   name: "authorizedPersonPan",
  //   //   isEdit: true,
  //   //   required: true,
  //   // },
  //   // {
  //   //   label: "VCN No",
  //   //   name: "vcnNo",
  //   //   isEdit: true,
  //   //   required: true,
  //   // },
  //   // {
  //   //   label: "CSN No",
  //   //   name: "csnNo",
  //   //   isEdit: true,
  //   // },
  //   // {
  //   //   label: "CSN Date",
  //   //   name: "csnDate",
  //   //   type: "date",
  //   //   isEdit: true,
  //   // },
  // ],
  hblFields: [
    {
      label: "HBL No",
      name: "hblNo",
      isEdit: true,
      required: true,
    },
    {
      label: "HBL Date",
      name: "hblDate",
      type: "date",
      isEdit: true,
      required: true,
    },
    {
      label: "CIN Type",
      name: "cinType",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      searchColumn: "m.name",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      where: "m.masterListName = 'tblCINType'",
      isEdit: true,
    },
    {
      label: "CIN NO",
      name: "cinNo",
      isEdit: true,
    },
    {
      label: "CSN No",
      name: "csnNo",
      isEdit: true,
    },
    {
      label: "CSN Date",
      name: "csnDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "Item Type",
      name: "itemNo",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      searchColumn: "m.name",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      where: "m.masterListName = 'tblItemType'",
      isEdit: true,
    },
    {
      label: "Nature of Cargo",
      name: "natureOfCargoId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      searchColumn: "m.name",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      where: "m.masterListName = 'tblTypeOfShipment'",
      style: "col-span-2 row-span-1",
      isEdit: true,
    },
    // {
    //   label: "Short Shipment",
    //   name: "shortShipment",
    //   type: "checkbox",
    //   isEdit: true,
    // },
    // {
    //   label: "FF Pan",
    //   name: "ffPan",
    //   type: "dropdown",
    //   labelType: "name,tblSubmitterType",
    //   foreignTable: "code-name,tblMasterData",
    //   isEdit: true,
    //   required: true,
    // },
    // {
    //   label: "FF Pan",
    //   name: "fffPan",
    //   isEdit: true,
    //   required: true,
    // },
  ],
  hblBottomFields: [
    {
      label: "CFS",
      name: "nominatedAreaId",
      type: "dropdown",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      tableName: "tblPort p",
      joins: "left join tblMasterData m on m.id = p.portTypeId",
      where: "m.code = 'CFS'",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      style: "col-span-3 row-span-1",
      isEdit: true,
    },
    {
      label: "DPD",
      name: "dpdId",
      type: "dropdown",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      tableName: "tblPort p",
      joins: "left join tblMasterData m on m.id = p.portTypeId",
      where: "m.code = 'DPD'",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      style: "col-span-3 row-span-1",
      isEdit: true,
    },
    {
      label: "Marks & Numbers",
      name: "marksNos",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-3 row-span-1 ",
      isEdit: true,
      required: true,
    },
    {
      label: "Goods & Description",
      name: "goodsDesc",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-3 row-span-1 ",
      isEdit: true,
      required: true,
    },
    // {
    //   label: "Invoice Value",
    //   name: "invoiceNo",
    //   isEdit: true,
    // },
    // {
    //   label: "Currency",
    //   name: "demurrageCurrencyId",
    //   type: "dropdown",
    //   tableName: "tblMasterData m",
    //   foreignTable: "code-name,tblMasterData",
    //   displayColumn: "m.name",
    //   where: "m.masterListName = 'tblCurrency'",
    //   isEdit: true,
    // },
    {
      label: "Cargo Gross Wt(Kgs)",
      name: "grossWt",
      type: "number",
      style: "col-span-2 row-span-1",
      required: true,
      // isEdit: true,
      disabled: true,
    },
    {
      label: "No of Package",
      name: "noOfPackages",
      type: "number",
      style: "col-span-2 row-span-1",
      // isEdit: true,
      required: true,
      disabled: true,
    },
    {
      label: "Package Type",
      name: "packageId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblPackage'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      style: "col-span-2 row-span-1",
      required: true,
      // isEdit: true,
      disabled: true,
    },
  ],
  consignorFields: [
    {
      label: "Name",
      name: "shipperText",
      required: true,
      isEdit: true,
    },
    {
      label: "Type",
      name: "shipperTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblIdentificationType'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      isEdit: true,
    },
    {
      label: "City",
      name: "shipperCity",
      type: "dropdown",
      tableName: "tblCity t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCity",
      required: true,
      isEdit: true,
      changeFun: "setCountryAndState",
    },
    {
      label: "Country",
      name: "shipperCountry",
      type: "dropdown",
      tableName: "tblCountry t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCountry",
      required: true,
      isEdit: true,
    },
    {
      label: "Address",
      name: "shipperAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      required: true,
      isEdit: true,
    },
  ],
  consigneeFields: [
    {
      label: "Name",
      name: "consigneeText",
      isEdit: true,
      required: true,
    },
    {
      label: "Type",
      name: "consigneeTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblIdentificationType'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      isEdit: true,
    },
    { label: "Code", name: "consigneeIdNo", isEdit: true, required: true },
    {
      label: "City",
      name: "consigneeCity",
      type: "dropdown",
      tableName: "tblCity t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCity",
      isEdit: true,
      required: true,
      changeFun: "setCountryAndState",
    },
    {
      label: "State",
      name: "consigneeState",
      type: "dropdown",
      tableName: "tblState t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblState",
      isEdit: true,
    },
    {
      label: "Country",
      name: "consigneeCountry",
      type: "dropdown",
      tableName: "tblCountry t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCountry",
      isEdit: true,
      required: true,
    },
    {
      label: "Address",
      name: "consigneeAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
      required: true,
    },
  ],
  notifyFields: [
    {
      label: "Name",
      name: "notifyPartyText",
      isEdit: true,
      required: true,
    },
    { label: "PAN Number", name: "notifyParty1IdNo", isEdit: true },
    {
      label: "City",
      name: "notifyParty1City",
      type: "dropdown",
      tableName: "tblCity t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCity",
      isEdit: true,
      required: true,
      changeFun: "setCountryAndState",
    },
    {
      label: "State",
      name: "notifyParty1State",
      type: "dropdown",
      tableName: "tblState t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblState",
      isEdit: true,
    },
    {
      label: "Country",
      name: "notifyParty1Country",
      type: "dropdown",
      tableName: "tblCountry t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCountry",
      isEdit: true,
      required: true,
    },
    {
      label: "Address",
      name: "notifyPartyAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
      required: true,
    },
  ],
  invoiceFields: [
    {
      label: "Invoicing Consignee Name",
      name: "billingParty",
      style: "col-span-2 row-span-1",
      isEdit: true,
    },
    {
      label: "GSTIN No",
      name: "billingPartyTaxNo",
      style: "col-span-2 row-span-1",
      isEdit: true,
    },
    {
      label: "Address",
      name: "billingPartyAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
    },
  ],
  tblBlContainer: [
    {
      label: "CONTAINER NO",
      name: "containerNo",
      isEdit: true,
      required: true,
      blurFun: "containerNumberHandler",
    },
    {
      label: "Size",
      name: "sizeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblSize'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      isEdit: true,
      changeFun: "setISOBySize",
    },
    {
      label: "Type",
      name: "typeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblType'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      isEdit: true,
      changeFun: "setISOByType",
    },
    {
      label: "ISO Code",
      name: "isoCode",
      type: "dropdown",
      tableName: "tblIsocode m",
      displayColumn: "m.isocode",
      foreignTable: "isocode,tblIsocode",
      isEdit: true,
      required: true,
    },
    {
      label: "Seal Type",
      name: "sealTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblSealType'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      isEdit: true,
    },
    { label: "Seal No.", name: "agentSealNo", isEdit: true },
    {
      label: "SOC Flag",
      name: "soc",
      isEdit: true,
      type: "checkbox",
    },
    // {
    //   label: "Container Agent Code",
    //   name: "Agent",
    //   isEdit: true,
    //   required: true,
    // },
    {
      label: "Cargo Gross Wt(Kgs)",
      name: "grossWt",
      type: "number",
      isEdit: true,
      required: true,
      blurFun: "countHandler",
    },
    { label: "NetWt(Kgs)", name: "netWt", type: "number", isEdit: true },
    {
      label: "Volume(CBM)",
      name: "volume",
      type: "number",
      isEdit: true,
    },
    {
      label: "NO of Package",
      name: "noOfPackages",
      type: "number",
      isEdit: true,
      required: true,
      blurFun: "countHandler",
    },
    {
      label: "Package Type",
      name: "packageId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblPackage' and m.principalCode IS  NULL",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      required: true,
      isEdit: true,
    },
  ],
  tblBlPackingList: [
    { label: "HS No", name: "hsnCode", isEdit: true, required: true },
    {
      label: "Cargo Item Description",
      name: "commodity",
      isEdit: true,
      required: true,
    },
    // {
    //   label: "UNO Code",
    //   name: "imoId",
    //   type: "dropdown",
    //   tableName: "tblImo m",
    //   displayColumn: "m.class",
    //   orderBy: "m.class",
    //   foreignTable: "class,tblImo",
    //   isEdit: true,
    // },
    {
      label: "UNO/IMO Code",
      name: "imoId",
      type: "dropdown",
      tableName: "tblImo m",
      displayColumn: "ISNULL(m.unNo,'') + ' - ' + ISNULL(m.class,'')",
      searchColumn: "m.unNo",
      orderBy: "m.unNo, m.class",
      foreignTable: "unNo-class,tblImo",
      isEdit: true,
    },
    {
      label: "No of Packages",
      name: "noOfPackages",
      type: "number",
      isEdit: true,
      required: true,
    },
    {
      label: "Package Type",
      name: "packageId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblPackage'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      isEdit: true,
      required: true,
    },
  ],
  tblAttachement: [
    {
      label: "Upload File",
      name: "path",
      type: "fileupload",
      isEdit: true,
      required: true,
    },
  ],
};

export const totalFieldData = {
  totalFields: [
    { label: "Total Gross Wt(Kgs)", name: "grossWt" },
    { label: "Total No of Packages", name: "packages" },
  ],
};

export const mapping = {
  notifyPartyText: "consigneeText",
  notifyParty1IdNo: "consigneeIdNo",
  notifyParty1Country: "consigneeCountry",
  notifyParty1State: "consigneeState",
  notifyParty1City: "consigneeCity",
  notifyPartyAddress: "consigneeAddress",
};

export const advanceSearchFields = {
  bl: [
    {
      label: "Vessel-Voyage No.",
      name: "podvesselId",
      type: "multiselect",
      tableName: "tblVessel v",
      displayColumn: "ISNULL(v.name,'') + ' - ' + ISNULL(vo.voyageNo,'')",
      joins: "left JOIN tblVoyage vo ON vo.vesselId = v.id",
      searchColumn: "v.name",
      orderBy: "v.name, vo.voyageNo",
      foreignTable: "name,tblVessel",
      isEdit: true,
    },
    {
      label: "MBL No",
      name: "mblNo",
      isEdit: true,
    },
    {
      label: "HBL No",
      name: "hblNo",
      isEdit: true,
    },
    {
      label: "Status",
      name: "hblRequestStatus",
      type: "multiselect",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblHblStatus'",
      orderBy: "m.name",
      isEdit: true,
    },
    {
      label: "Type of Cargo",
      name: "cargoTypeId",
      type: "multiselect",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblCargoType'",
      orderBy: "m.name",
      isEdit: true,
    },
  ],
};

export const gridButtons = [
  {
    text: "Add Row",
    icon: <AddIcon />,
    func: "gridAddHandler",
  },
  {
    text: "Delete Row",
    icon: <CloseIcon />,
    func: "gridDeleteHandler",
  },
  {
    text: "Copy Row",
    icon: <FileCopyIcon />,
    func: "gridCopyHandler",
  },
  {
    text: "Import Excel",
    icon: <UploadFileIcon />,
    func: "excelUpload",
  },
];

export const gridButtonsWithoutExcel = [
  {
    text: "Add Row",
    icon: <AddIcon />,
    func: "gridAddHandler",
  },
  {
    text: "Delete Row",
    icon: <CloseIcon />,
    func: "gridDeleteHandler",
  },
  {
    text: "Copy Row",
    icon: <FileCopyIcon />,
    func: "gridCopyHandler",
  },
];
