import AddIcon from "@mui/icons-material/Add";
import CloseIcon from "@mui/icons-material/Close";

export const fieldData = {
  fields: [
    {
      label: "Location",
      name: "locationId",
      type: "dropdown",
      isEdit: true,
      required: true,
      tableName: "tblLocation p",
      displayColumn: "p.name",
      orderBy: "p.name",
      where: "p.status = 1",
      foreignTable: "name,tblLocation",
      disabled: true,
    },
    {
      label: "Liner",
      name: "shippingLineId",
      type: "dropdown",
      tableName: "tblCompany t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCompany",
      required: true,
      isEdit: true,
      changeFun: "setCfsAndDpd",
    },
    {
      label: "MBL No",
      name: "blNo",
      type: "text",
      isEdit: true,
      required: true,
      blurFun: "duplicateHandler",
      // blurFun: "getDataBasedonLinerAndBLNo",
    },
    // {
    //   label: "MBL Date",
    //   name: "mblDate",
    //   type: "date",
    //   isEdit: true,
    //   required: true,
    // },
    // {
    //   label: "Vessel",
    //   name: "podVesselId",
    //   type: "dropdown",
    //   tableName: "tblVessel t",
    //   idColumn: "id",
    //   displayColumn: "t.name",
    //   searchColumn: "t.name",
    //   orderBy: "t.name",
    //   foreignTable: "name,tblVessel",
    //   isEdit: true,
    // },
    // {
    //   label: "Voyage",
    //   name: "podVoyageId",
    //   type: "dropdown",
    //   tableName: "tblVoyage t",
    //   idColumn: "id",
    //   displayColumn: "t.voyageNo",
    //   searchColumn: "t.voyageNo",
    //   selectedConditions: [{ podVesselId: "vesselId" }],
    //   orderBy: "t.voyageNo",
    //   foreignTable: "voyageNo,tblVoyage",
    //   isEdit: true,
    // },
    // {
    //   label: "Place of Delivery",
    //   name: "fpdId",
    //   type: "dropdown",
    //   tableName: "tblPort p",
    //   displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
    //   orderBy: "p.name",
    //   foreignTable: "code-name,tblPort",
    //   required: true,
    //   isEdit: true,
    // },
    // {
    //   label: "Consignee Name",
    //   name: "consigneeText",
    //   type: "text",
    //   isEdit: true,
    // },
    {
      label: "CFS Type",
      name: "cfsTypeId",
      type: "dropdown",
      isEdit: true,
      required: true,
      displayColumn: "m.name",
      tableName: "tblMasterData m",
      where: "masterListName  = 'tblCfsType'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      changeFun: "setCfsType",
    },
    {
      label: "CFS",
      name: "nominatedAreaId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      joins:
        "join tblMasterData m on m.id = p.portTypeId  and m.masterListName = 'tblPortType' and m.code = 'CFS' and p.companyId = null",
      isEdit: true,
      foreignTable: "code-name,tblPort",
      required: true,
    },
    {
      label: "DPD",
      name: "dpdId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      joins:
        "join tblMasterData m on m.id = p.portTypeId  and m.masterListName = 'tblPortType' and m.code = 'DPD' and p.companyId = null",
      isEdit: true,
      foreignTable: "name,tblPort",
    },
    {
      label: "Nominated CB",
      name: "customBrokerText",
      type: "text",
      isEdit: true,
    },
    // {
    //   label: "Status",
    //   name: "cfsRequestStatusId",
    //   type: "dropdown",
    //   isEdit: false,
    //   tableName: "tblMasterData m",
    //   displayColumn: "m.name",
    //   where: "masterListName = 'tblCfsStatusType'",
    //   foreignTable: "name,tblMasterData",
    //   isEdit: true,
    //   orderBy: "m.name",
    //   disabled: true,
    // },
    {
      label: "Remark",
      name: "remarks",
      type: "textarea",
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
    },
  ],

  tblAttachment: [
    {
      label: "Select",
      name: "attachmentTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      idColumn: "id",
      displayColumn: "m.name",
      searchColumn: "m.name",
      orderBy: "m.name",
      where: "m.masterListName = 'tblCfsAttachmentType'",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
    {
      label: "Upload File",
      name: "path",
      type: "fileupload",
      isEdit: true,
      required: true,
    },
  ],
};

// export const cfsData = [
//   { label: "Country Code", value: "code" },
//   { label: "Country Name", value: "name" },
// ];

export const tblColsLables = [
  ...fieldData.fields.filter((f) => f.label !== "Remark").map((f) => f.label),
  "Status",
  fieldData.fields.find((f) => f.label === "Remark")?.label,
].filter(Boolean);

export const cfsGridButtons = [
  { text: "Add", icon: <AddIcon />, func: "gridAddHandler" },
  { text: "Delete", icon: <CloseIcon />, func: "gridDeleteHandler" },
];

export const advanceSearchFields = {
  bl: [
    {
      label: "Liner",
      name: "shippingLineId",
      type: "multiselect",
      tableName: "tblCompany t",
      displayColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "BL No",
      name: "blNo",
      isEdit: true,
    },
    {
      label: "CFS",
      name: "nominatedAreaId",
      type: "multiselect",
      tableName: "tblPort p",
      displayColumn: "p.name",
      joins: `join tblMasterData m on m.id = p.portTypeId  and m.masterListName = 'tblPortType' and m.code = 'CFS'`,
      isEdit: true,
    },
    {
      label: "Status",
      name: "cfsRequestStatusId",
      type: "multiselect",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblCfsStatusType'",
      orderBy: "m.name",
      isEdit: true,
    },
  ],
  shipBl: [
    {
      label: "Company Name",
      name: "companyId",
      type: "multiselect",
      tableName: "tblCompany t",
      displayColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "BL No",
      name: "blNo",
      isEdit: true,
    },
    {
      label: "CFS",
      name: "nominatedAreaId",
      type: "multiselect",
      tableName: "tblPort p",
      displayColumn: "p.name",
      joins: `join tblMasterData m on m.id = p.portTypeId  and m.masterListName = 'tblPortType' and m.code = 'CFS'`,
      isEdit: true,
    },
    {
      label: "Status",
      name: "cfsRequestStatusId",
      type: "multiselect",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblCfsStatusType'",
      orderBy: "m.name",
      isEdit: true,
    },
  ],
};
