import { getUserByCookies } from "@/utils";

const userData = getUserByCookies();

const fieldData = {
  igmEdiFields: [
    {
      label: "Vessel",
      name: "vessel",
      type: "dropdown",
      tableName: "tblVessel t",
      idColumn: "id",
      changeFun: "handleChangeOnVessel",
      displayColumn: "t.name",
      searchColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "Voyage",
      name: "voyage",
      type: "dropdown",
      tableName: "tblVoyage t",
      displayColumn: "t.voyageNo",
      searchColumn: "t.voyageNo",
      changeFun: "handleDropdownChange",
      selectedConditions: [{ vessel: "vesselId" }],
      where: `t.status = 1 and t.companyid = ${userData?.companyId}`,
      orderBy: "t.voyageNo",
      isEdit: true,
    },
    {
      label: "POD",
      name: "pod",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      changeFun: "handleDropdownChange",
      joins: `join tblMasterData d on p.portTypeId = d.id and d.name = 'SEA PORT' join tblVoyageRoute v on v.portOfCallId = p.id`,
      selectedConditions: [{ voyage: "v.voyageId" }],
      searchColumn: "p.name",
      whereCondition: "p.status = 1",
      orderBy: "p.name",
      isEdit: true,
    },
    {
      label: "FPD",
      name: "fpd",
      type: "dropdown",
      tableName: "tblPort t",
      idColumn: "id",
      joins:
        "JOIN tblMasterData m ON m.id = t.portTypeId JOIN tblCountry c ON c.id = t.countryId",
      where: "m.name IN ('INLAND PORT') and c.name = 'India'",
      displayColumn: "t.name",
      searchColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "Terminal",
      name: "terminal",
      type: "dropdown",
      tableName: "tblPort p",
      idColumn: "id",
      displayColumn: "p.code",
      joins: `join tblMasterData d on p.portTypeId = d.id and d.name = 'PORT TERMINAL' join tblVoyageRoute v on v.berthId = p.id`,
      selectedConditions: [
        { pod: "p.referencePortId" },
        { voyage: "v.voyageId" },
        { vessel: "v.vesselId" },
      ],
      whereCondition: "v.status = 1",
      searchColumn: "p.code",
      orderBy: "p.code",
      changeFun: "handleDropdownChange",
      isEdit: true,
    },
    {
      label: "Movement Carrier",
      name: "movementCarrierId",
      type: "dropdown",
      displayColumn: "c.code",
      searchColumn: "c.code",
      tableName: "tblCompany c",
      joins: `join tblCompanySubtype cs on cs.companyId = c.id join tblUser u2 on u2.id = cs.subTypeId and u2.roleCode = 'CTO'`,
      orderBy: "c.name",
      foreignTable: "name,tblCompany",
      isEdit: true,
    },
    {
      label: "Text file",
      name: "textFile",
      type: "checkbox",
      isEdit: true,
    },
  ],
};

export default fieldData;

export const metaData = [
  // {
  //   name: "Voyage",
  //   isEdit: true,
  // },
  // {
  //   name: "BL No",
  //   isEdit: true,
  // },
  // {
  //   name: "Gross Wt",
  //   type:"number",
  //   isEdit: true,
  // },
  // {
  //   // label: "Location(POD)",
  //   name: "Place of Receipt",
  //   type: "dropdown",
  //   labelType: "pod",
  //   foreignTable: "name,tblPort",
  //   isEdit: true,
  // },
  // {
  //   // label: "Location(POD)",
  //   name: "Port of Loading",
  //   type: "dropdown",
  //   labelType: "pod",
  //   foreignTable: "name,tblPort",
  //   isEdit: true,
  // },
  // {
  //   // label: "Location(POD)",
  //   name: "Port of Discharge",
  //   type: "dropdown",
  //   labelType: "pod",
  //   foreignTable: "name,tblPort",
  //   isEdit: true,
  // },
  // {
  //   // label: "Location(POD)",
  //   name: "Final Place of Delivery",
  //   type: "dropdown",
  //   labelType: "pod",
  //   foreignTable: "name,tblPort",
  //   isEdit: true,
  // },
];
