import AddIcon from "@mui/icons-material/Add";
import CloseIcon from "@mui/icons-material/Close";
const fieldData = {
  companyFields: [
    {
      label: "Company Code",
      name: "code",
      isEdit: true,
      required: true,
    },
    {
      label: "Company Name",
      name: "name",
      isEdit: true,
      required: true,
    },
    {
      label: "Country Name",
      name: "countryId",
      type: "dropdown",
      tableName: "tblCountry t",
      foreignTable: "name,tblCountry",
      displayColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
      required: true,
    },
    {
      label: "State/Region",
      name: "stateId",
      type: "dropdown",
      tableName: "tblState t",
      displayColumn: "t.name",
      foreignTable: "name,tblState",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "City Name",
      name: "cityId",
      type: "dropdown",
      tableName: "tblCity t",
      displayColumn: "t.name",
      foreignTable: "name,tblCity",
      selectedConditions: [{ countryId: "countryId" }],
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "Company Address",
      name: "address",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
      required: true,
    },
    {
      label: "Zip Code",
      name: "pincode",
      isEdit: true,
    },
    {
      label: "Phone",
      name: "telephoneNo",
      type: "number",
      isEdit: true,
    },
    {
      label: "Email ID",
      name: "emailId",
      isEdit: true,
    },
    {
      label: "Pan No",
      name: "panNo",
      isEdit: true,
      blurFun: "validatePanCard",
      required: true,
    },

    {
      label: "GSTIN No",
      name: "taxRegistrationNo",
      isEdit: true,
      blurFun: "validateGstNO",
      required: true,
    },
    {
      label: "Company Group Name",
      name: "companyGroupId",
      type: "dropdown",
      tableName: "tblMasterData m",
      foreignTable: "name,tblMasterData",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblCompanyGroup'",
      isEdit: true,
    },
    {
      label: "Credit Period",
      name: "creditPeriod",
      type: "number",
      isEdit: true,
    },
    {
      label: "Currency",
      name: "currencyId",
      type: "dropdown",
      tableName: "tblMasterData m",
      foreignTable: "name,tblMasterData",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblCurrency'",
      isEdit: true,
    },
    {
      label: "IEC No",
      name: "importExportCode",
      isEdit: true,
      blurFun:"validateIecNO"
    },
    {
      label: "Website",
      name: "website",
      isEdit: true,
    },
    {
      label: "Remarks",
      name: "remarks",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
    },
  ],
  tblCompanyBranch: [
    {
      label: "Branch Code",
      name: "code",
      isEdit: true,
      required: "true",
    },
    {
      label: "Branch Name",
      name: "name",
      isEdit: true,
      required: "true",
    },
    {
      label: "Country",
      name: "countryId",
      type: "dropdown",
      tableName: "tblCountry t",
      foreignTable: "name,tblCountry",
      displayColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "State",
      name: "stateId",
      type: "dropdown",
      tableName: "tblState t",
      displayColumn: "t.name",
      foreignTable: "name,tblState",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "City",
      name: "cityId",
      type: "dropdown",
      tableName: "tblCity t",
      displayColumn: "t.name",
      foreignTable: "name,tblCity",
      selectedConditions: [{ countryId: "countryId" }],
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "GSTIN No",
      name: "taxRegistrationNo",
      isEdit: true,
      blurFun: "validateGstNO",
    },
    {
      label: "Zipcode",
      name: "pincode",
      isEdit: true,
      required: true,
    },
    {
      label: "Telephone No",
      name: "telephoneNo",
      isEdit: true,
      required: true,
    },
    {
      label: "Email Id",
      name: "emailId",
      isEdit: true,
      required: true,
    },

    {
      label: "Language",
      name: "languageId",
      type: "dropdown",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
    {
      label: "Branch address",
      name: "address",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
    },
    {
      label: "Remarks",
      name: "remarks",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
      required: true,
    },
  ],
};

export const company = [
  { label: "Code", value: "co.code" },
  { label: "Name", value: "co.name" },
  { label: "Country Name", value: "c.name" },
  { label: "State Name", value: "s.name" },
  { label: "City Name", value: "ci.name" },
  { label: "Phone No", value: "co.telephoneNo" },
  { label: "Email Id", value: "co.emailId " },
  { label: "Pan No", value: "co.panNo " },
  { label: "GSTIN No", value: "co.taxRegistrationNo" },
];

export default fieldData;
export const branchGridButtons = [
  {
    text: "Add ",
    icon: <AddIcon />,
    func: "gridAddHandler",
  },
  {
    text: "Delete ",
    icon: <CloseIcon />,
    func: "gridDeleteHandler",
  },
];
