const fieldData = {
  companyFields: [
    {
      label: "Company Code",
      name: "code",
      isEdit: "true",
    },
    {
      label: "Company Name",
      name: "name",
      isEdit: "true",
    },
    {
      label: "Country Name",
      name: "countryId",
      type: "dropdown",
      labelType: "country",
      foreignTable: "name,tblCountry",
      isEdit: "true",
    },
    {
      label: "State/Region Name",
      name: "stateId",
      type: "dropdown",
      labelType: "state",
      foreignTable: "name,tblState",
      isEdit: "true",
    },
    {
      label: "City Name",
      name: "cityId",
      type: "dropdown",
      labelType: "city",
      selectedCondition: "countryId",
      foreignTable: "name,tblCity",
      isEdit: "true",
    },
    {
      label: "Company Address",
      name: "address",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: "true",
    },
    {
      label: "Zip Code",
      name: "pincode",
      isEdit: "true",
    },
    {
      label: "Phone",
      name: "telephoneNo",
      type: "number",
      isEdit: "true",
    },
    {
      label: "Email ID",
      name: "emailId",
      isEdit: "true",
    },
    {
      label: "Pan No",
      name: "panNo",
      isEdit: "true",
    },
    {
      label: "Remarks",
      name: "remarks",
      multiline: true,
      rows: 1,
      type: "textarea",
      isEdit: true,
      isEdit: "true",
    },
    {
      label: "GSTIN No",
      name: "taxRegistrationNo",
      isEdit: "true",
    },
    {
      label: "Company Group Name",
      name: "companyGroupId",
      type: "dropdown",
      labelType: "name,tblCompanyGroup",
      foreignTable: "name,tblMasterData",
      isEdit: "true",
    },
    {
      label: "Credit Period",
      name: "creditPeriod",
      type: "number",
      isEdit: "true",
    },
    {
      label: "Currency",
      name: "currencyId",
      type: "dropdown",
      labelType: "code,tblCurrency",
      foreignTable: "name,tblMasterData",
      isEdit: "true",
    },
    {
      label: "IEC No",
      name: "importExportCode",
      isEdit: "true",
    },
    {
      label: "Website",
      name: "website",
      isEdit: "true",
    },
  ],
};

export default fieldData;
