export const roleAccessPaths = {
  "/menu-access": ["admin"],
  "/reports": ["admin", "shipping", "customer", "cfs"],

  "/bl-status": ["admin", "shipping", "customer", "cfs"],
  "/bl/hbl/list": ["admin", "customer"],
  "/bl/hbl/upload": ["customer", "admin"],
  "/bl/hbl/linerSearch": ["shipping", "admin"],
  "/bl/mbl/list": ["shipping", "admin"],
  "/bl/cfs-request/list": ["admin" , "customer"],




  "/request": ["admin", "shipping", "customer", "cfs"],
  "/htmlReports/igmReports": ["admin", "shipping", "customer", "cfs"],
  "/upload": ["admin", "shipping", "customer", "cfs"],
  "/blPartyHold": ["admin", "shipping", "customer", "cfs"],
  "/home": ["admin", "shipping", "customer", "cfs"],
  "/request/doRequest/list": ["shipping", "customer"],

  "/reports/customAndPort/cfsDpdIcd": ["shipping"],
  "/reports/customAndPort/hbl": ["shipping", "customer"],
  "/reports/customAndPort/vesselSummaryReport": ["shipping"],
  "/reports/customAndPort/igmGenerationAuditReport": ["shipping"],
  "/reports/customAndPort/doRegister": ["shipping"],
  "/reports/customAndPort/slabWiseReport": ["shipping"],

  // Added master routes with only admin access
  "/master/company/list": ["admin"],
  "/master/containerSize/list": ["admin"],
  "/master/containerStatus/list": ["admin"],
  "/master/containerType/list": ["admin"],
  "/master/cfs/list": ["admin", "shipping"],
  "/master/depot/list": ["admin"],
  "/master/isoCode/list": ["admin"],
  "/master/imo/list": ["admin"],
  "/master/itemType/list": ["admin"],
  "/master/cargoType/list": ["admin"],
  "/master/country/list": ["admin"],
  "/master/state/list": ["admin"],
  "/master/city/list": ["admin"],
  "/master/vessel/list": ["admin", "shipping"],
  "/master/voyageRoute/list": ["admin", "shipping"],
  "/master/voyage/list": ["admin", "shipping"],
  "/master/port/list": ["admin"],
  "/master/terminal/list": ["admin"],
  "/master/dpd/list": ["admin", "shipping"],
  "/master/typeOfCompany/list": ["admin"],
  "/master/packageType/list": ["admin"],
  "/master/user/list": ["admin"],
  "/master/unit/list": ["admin"],
  "/master/unitType/list": ["admin"],
  "/master/modeOfTransport/list": ["admin"],
  "/master/movementType/list": ["admin"],
  "/master/berthAgent/list": ["admin", "shipping"],
  "/master/carrierPort/list": ["admin", "shipping"],
};
