export const dropdowns = {
  country: [
    { label: "Country Code", value: "code" },
    { label: "Country Name", value: "name" },
  ],
  state: [
    { label: "Code", value: "s.code" },
    { label: "Tax State Code", value: "s.taxStateCode" },
    { label: "Name", value: "s.name" },
    { label: "Country Name", value: "c.name" },
  ],
  city: [
    { label: "City Name", value: "c.name" },
    { label: "State Name", value: "s.name" },
    { label: "Country Name", value: "co.name" },
  ],
  port: [
    { label: "Code", value: "p.code" },
    { label: "Port Name", value: "p.name" },
    { label: "ActiveInactive", value: "p.activeInactive" },
    { label: "Port Type Name", value: "m.name" },
    { label: "Country", value: "c.name" },
  ],

  ContainerStatus: [
    { label: " Name", value: "m.name" },
    { label: "Code", value: "m.code" },
  ],
  depot: [
    { label: "Location", value: "m.name" },
    { label: "Depot Code", value: "p.code" },
    { label: "Depot name", value: "p.name" },
    { label: "Address", value: "p.address" },
  ],
  vessel: [
    { label: " Code", value: "code" },
    { label: "Name", value: "name" },
  ],
  Commodity: [
    { label: " Code", value: "code" },
    { label: "Name", value: "name" },
  ],
  VoyageRoute: [
    { label: "Port of Call", value: "p.name" },
    { label: "Voyage No", value: "v.voyageId" },
    { label: "Vessel No", value: "ve.name" },
    { label: "IGM NO", value: "v.igmNo" },
    { label: "Export Locking", value: "v.exportLocking" },
    { label: "Import Locking", value: "v.importLocking" },
    { label: "Terminal", value: "p.name" },
    { label: "Voyage", value: "v.voyageNo" },
  ],
  typeOfCompany: [
    { label: "Company SubType Code", value: "code" },
    { label: "Company SubType", value: "name" },
  ],
  company: [
    { label: "Code", value: "co.code" },
    { label: "Name", value: "co.name" },
    { label: "Country Name", value: "c.name" },
    { label: "State Name", value: "s.name" },
    { label: "City Name", value: "ci.name" },
    { label: "Phone No", value: "co.telephoneNo" },
    { label: "Email Id", value: "co.emailId " },
    { label: "Pan No", value: "co.panNo " },
    { label: "GSTIN No", value: "co.taxRegistrationNo" },
  ],
  unit: [
    { label: " Name", value: "m.name" },
    { label: "Code", value: "m.code" },
  ],
  unitType: [
    { label: " Name", value: "m.name" },
    { label: "Code", value: "m.code" },
  ],
  itemType: [
    { label: " Name", value: "m.name" },
    { label: "Code", value: "m.code" },
  ],
  cargoType: [
    { label: " Name", value: "m.name" },
    { label: "Code", value: "m.code" },
  ],
  packageType: [
    { label: " Name", value: "m.name" },
    { label: "Code", value: "m.code" },
  ],
  companyBranch: [
    { label: "Code", value: "co.code" },
    { label: "Name", value: "co.name" },
    { label: "Company Branch", value: "com.name" },
    { label: "Country Name", value: "c.name" },
    { label: "State Name", value: "s.name" },
    { label: "City Name", value: "ci.name" },
    { label: "Phone No", value: "co.telephoneNo" },
    { label: "GSTIN No", value: "co.taxRegistrationNo" },
    { label: "ZipCode", value: "co.pincode" },
  ],
  isoCode: [
    { label: "IsoCode", value: "i.isoCode" },
    { label: "Size", value: "sizeData.name" },
    { label: "Type", value: "typeData.name" },
  ],
  imo: [
    { label: "UnNo", value: "i.unNo" },
    { label: "Class", value: "i.class" },
    { label: "FlashPoint", value: "m.flashPoint" },
  ],
  ContainerSize: [
    { label: "Size", value: "m.name" },
    { label: "Code", value: "m.code" },
  ],
  ContainerType: [
    { label: " Name", value: "m.name" },
    { label: "Code", value: "m.code" },
  ],
  SmtpCarrier: [
    { label: "Code", value: "co.code" },
    { label: "Name", value: "co.name" },
    { label: "Country Name", value: "c.name" },
    { label: "State Name", value: "s.name" },
    { label: "City Name", value: "ci.name" },
    { label: "Phone No", value: "co.telephoneNo" },
    { label: "Email Id", value: "co.emailId " },
    { label: "Pan No", value: "co.panNo " },
    { label: "GSTIN No", value: "co.taxRegistrationNo" },
  ],
  movementType: [
    { label: " Name", value: "m.name" },
    { label: "Code", value: "m.code" },
  ],
  modeOfTransport: [
    { label: " Name", value: "m.name" },
    { label: "Code", value: "m.code" },
  ],
  bl: [
    { label: "MBL NO", value: "b.mblNo" },
    { label: "MBL DATE", value: "b.mblDate" },
    { label: "Consignee Text", value: "b.consigneeText" },
    { label: "POL", value: "p.name" },
    { label: "POD", value: "p1.name" },
    { label: "FPD", value: "p2.name" },
    { label: "Cargo Movement", value: "m.name" },
    { label: "Arrival Vessel", value: "v1.name" },
    { label: "Arrival Voyage", value: "v.voyageNo" },
    { label: "Line NO", value: "b.itemNo" },
  ],
  voyage: [
    { label: "Vessel Name", value: "v1.name" },
    { label: "Voyage No", value: "v.voyageNo" },
  ],
  user: [
    { label: "Name", value: "name" },
    { label: "Email Id", value: "emailId" },
    { label: "Phone No", value: "mobile" },
  ],
  terminal: [
    { label: "Port/Location", value: "m.name" },
    { label: "Terminal", value: "p.name" },
  ],
};
