const fieldData = {
  fields: [
    {
      label: "Department",
      name: "department",
      type: "dropdown",
      labelType: "department",
    },
    {
      label: "MBL No.",
      name: "mblNo",
    },
    {
      label: "MBL Date",
      name: "bookingReferenceNo",
      type: "date",
    },
    {
      label: "Line No.",
      name: "lineNo",
    },
    {
      label: "MLO",
      name: "mlo",
      type: "mlo",
      labelType: "mlo",
    },
    {
      label: "SOC",
      name: "soc",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
    },
  ],
  consignorFields: [
    {
      label: "Shipper Name",
      name: "shipperName",
      style: "mb-2",
      isEdit: true,
    },
    {
      label: "Shipper Address",
      name: "shipperAddress",
      style: "sm:w-[min(100%,300px)]",
      multiline: true,
      rows: 6,
      type: "textarea",
      isEdit: true,
    },
  ],
  consigneeFields: [
    {
      label: "Consignee Name",
      name: "consigneeName",
      style: "mb-2",
      isEdit: true,
    },
    {
      label: "Consignee Address",
      name: "consigneeAddress",
      style: "sm:w-[min(100%,300px)]",
      multiline: true,
      rows: 6,
      type: "textarea",
      isEdit: true,
    },
  ],
  notifyFields: [
    {
      label: "Notify Name",
      name: "notifyName",
      style: "mb-2",
      isEdit: true,
    },
    {
      label: "Notify Address",
      name: "notifyAddress",
      style: "sm:w-[min(100%,300px)]",
      multiline: true,
      rows: 6,
      type: "textarea",
      isEdit: true,
    },
  ],
  deliveryAgentFields: [
    {
      label: "Notify2 Name",
      name: "notify2Name",
      style: "mb-2",
      isEdit: true,
    },
    {
      label: "Notify2 Address",
      name: "notify2Address",
      style: "sm:w-[min(100%,300px)]",
      multiline: true,
      rows: 6,
      height: "auto",
      type: "textarea",
      isEdit: true,
    },
  ],
  shipmentFields: [
    {
      label: "Type of Shipment",
      name: "typeofShipment",
      type: "dropdown",
      labelType: "name,tblTypeOfShipment",
    },
    {
      label: "Container Status",
      name: "containerStatus",
      type: "dropdown",
      labelType: "name,tblContainerStatus",
    },
    {
      label: "Free Days at destination",
      name: "freeDaysAtDestination",
    },
    {
      label: "Detention",
      name: "detention",
      type: "dropdown",
      labelType: "PORT",
    },
    {
      label: "Jumping Slab",
      name: "jumpingSlab",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
    },
    {
      label: "Slab",
      name: "slab",
    },
    {
      label: "Route",
      name: "route",
      type: "dropdown",
      labelType: "name,tblRoutingType",
    },
  ],
  transportFields: [
    {
      label: "Shipping Line",
      name: "shippingLine",
      type: "dropdown",
      labelType: "company",
    },
    {
      label: "PLR",
      name: "plr",
      type: "dropdown",
      labelType: "port",
    },
    {
      label: "POL",
      name: "pol",
      type: "dropdown",
      labelType: "port",
    },
    {
      label: "POD",
      name: "pod",
      type: "dropdown",
      labelType: "port",
    },
    {
      label: "POD Agent",
      name: "podAgent",
      type: "dropdown",
      labelType: "company",
    },
    {
      label: "POD Agent Branch",
      name: "podAgentBranch",
      type: "dropdown",
      labelType: "companyBranch",
    },
    {
      label: "FPD",
      name: "fpd",
      type: "dropdown",
      labelType: "port",
    },
    {
      label: "FPD Agent",
      name: "fpdAgent",
      type: "dropdown",
      labelType: "company",
    },
    {
      label: "FPD Agent Branch",
      name: "fpdAgentBranch",
      type: "dropdown",
      labelType: "companyBranch",
    },
    {
      label: "Departure Vessel",
      name: "departureVessel",
      type: "dropdown",
      labelType: "vessel",
    },
    {
      label: "Departure Voyage",
      name: "departureVoyage",
      type: "dropdown",
      labelType: "voyage",
    },
    {
      label: "Arrival Vessel",
      name: "arrivalVessel",
      type: "dropdown",
      labelType: "vessel",
    },
    {
      label: "Arrival Voyage",
      name: "arrivalVoyage",
      type: "dropdown",
      labelType: "voyage",
      selectedCondition: "arrivalVessel",
    },
    {
      label: "Cargo Movement",
      name: "cargoMovement",
      type: "dropdown",
      labelType: "name,tblMovementType",
    },
    {
      label: "Movement Carrier",
      name: "movementCarrier",
    },
    {
      label: "Pre-Carriage",
      name: "preCarriage",
      type: "dropdown",
      labelType: "name,tblMode",
    },
    {
      label: "Post-Carriage",
      name: "postCarriage",
      type: "dropdown",
      labelType: "name,tblMode",
    },
    {
      label: "SEZ",
      name: "SEZ",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
    },
    {
      label: "Consignee Nominated CFS",
      name: "consigneeNominatedCfs",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
    },
    {
      label: "CSF",
      name: "csf",
      type: "dropdown",
      labelType: "port",
    },
    {
      label: "Direct Port Delivery Code",
      name: "directPortDeliveryCode",
      type: "dropdown",
      labelType: "port",
    },
    {
      label: "DPD CFS",
      name: "dpdCfs",
      type: "dropdown",
      labelType: "port",
    },
  ],
  commodityFields: [
    {
      label: "Item Type",
      name: "itemType",
      type: "dropdown",
      labelType: "name,tblItemType",
    },
    {
      label: "Cargo Type",
      name: "cargoType",
      type: "dropdown",
      labelType: "name,tblCargoType",
    },
    {
      label: "Commodity Type",
      name: "commodityType",
      type: "dropdown",
      labelType: "name,tblCommodityType",
    },
    {
      label: "Commodity",
      name: "commodity",
    },
    {
      label: "Marks And Numbers",
      name: "marksAndNumbers",
      multiline: true,
      rows: 6,
      gridColumn: "col-span-1 row-span-3 ",
      type: "textarea",
      isEdit: true,
    },
    {
      label: "Remarks",
      name: "remarks",
      multiline: true,
      rows: 6,
      gridColumn: "col-span-1 row-span-3 ",
      type: "textarea",
      isEdit: true,
    },
    {
      label: "Description of Goods",
      name: "descriptionOfGoods",
      multiline: true,
      rows: 6,
      gridColumn: "col-span-1 row-span-3 ",
      type: "textarea",
      isEdit: true,
    },
    {
      label: "HS Code",
      name: "hsCode",
    },
    {
      label: "Gross Weight",
      name: "grossWeight",
      type: "number",
    },
    {
      label: "Net Weight",
      name: "netWeight",
      type: "number",
    },
    {
      label: "Gross Weight Unit",
      name: "grossWeightUnit",
      type: "dropdown",
      labelType: "code,tblUnit",
    },
    {
      label: "Cargo Volume",
      name: "cargoVolume",
      type: "number",
    },
    {
      label: "Cargo Volume Unit",
      name: "cargoVolumeUnit",
      type: "dropdown",
      labelType: "code,tblUnit",
    },
    {
      label: "No of Packages",
      name: "noOfPackages",
      type: "number",
    },
    {
      label: "Type of Packages",
      name: "typeOfPackages",
      type: "dropdown",
      labelType: "name,tblPackage",
    },
  ],
  containerFields1: [
    {
      label: "Container",
      name: "container",
      type: "dropdown",
      labelType: "container",
    },
    { label: "Container No.", name: "containerNo", type: "text" },
    {
      label: "Size",
      name: "size",
      type: "dropdown",
      labelType: "name,tblSize",
    },
    {
      label: "Type",
      name: "type",
      type: "dropdown",
      labelType: "name,tblType",
    },
    {
      label: "Status",
      name: "status",
      type: "dropdown",
      labelType: "name,tblContainerStatus",
    },
    { label: " Agent Seal No", name: "agentsealNo" },
    { label: "No Of Pkgs", name: "noOfPackages", type: "number" },
    {
      label: "Type Of Pkgs",
      name: "package",
      type: "dropdown",
      labelType: "name,tblPackage",
    },
    { label: "Net Weight", name: "netWeight", type: "number" },
    { label: "Tara Weight", name: "taraWeight", type: "number" },
    {
      label: "Gross Weight",
      name: "grossWeight",
      type: "number",
    },
    {
      label: "Gross Unit",
      name: "grossWeightUnit",
      type: "dropdown",
      labelType: "name,tblUnit",
    },
    {
      label: "Reefer Temperature",
      name: "reeferTemperture",
      type: "number",
    },
    {
      label: "Ref Temp Unit",
      name: "refTempUnit",
      type: "dropdown",
      labelType: "name,tblUnit",
    },
    { label: "OOG Front", name: "oogFront", type: "number" },
    { label: "OOG Back", name: "backFront", type: "number" },
    {
      label: "OOG Back left",
      name: "oogBackLeft",
      type: "number",
    },
    {
      label: "ODC Dimension Unit",
      name: "dimensionUnit",
      type: "dropdown",
      labelType: "name,tblUnit",
    },
    { label: "OOGRight", name: "oogRight", type: "number" },
    { label: "OOGTop", name: "oogTop", type: "number" },
    { label: "Free Days", name: "freeDays" },
    {
      label: "Slot owner",
      name: "slotOwner",
      type: "dropdown",
      labelType: "company",
    },
  ],
};

export default fieldData;
