const fieldData = {
  voyageFields: [
    {
      label: "Port Of Call",
      name: "portOfCallId",
      type: "dropdown",
      labelType: "port",
      foreignTable: "name,tblPort",
      isEdit: true,
    },
    {
      label: "Vessel Name",
      name: "vesselId",
      type: "dropdown",
      labelType: "vessel",
      foreignTable: "name,tblVessel",
      isEdit: true,
    },
    {
      label: "Voyage No",
      name: "voyageId",
      type: "dropdown",
      labelType: "voyage",
      selectedCondition: "vesselId",
      foreignTable: "voyageNo,tblVoyage",
      isEdit: true,
    },
    {
      label: "Terminal",
      name: "berthId",
      type: "dropdown",
      labelType: "port",
      foreignTable: "name,tblPort",
      isEdit: true,
    },
    {
      label: "Export Voyage No",
      name: "exportExchangeRate",
      type: "number",
      isEdit: true,
    },
    {
      label: "Import Voyage No",
      name: "importExchangeRate",
      type: "number",
      isEdit: true,
    },
    {
      label: "ETA",
      name: "eta",
      type: "date",
      isEdit: true,
    },
    {
      label: "ETD",
      name: "etd",
      type: "date",
      isEdit: true,
    },
    {
      label: "ETB",
      name: "etb",
      type: "date",
      isEdit: true,
    },
    {
      label: "Port Cut Off",
      name: "portCutoff",
      type: "date",
      isEdit: true,
    },
  ],
  portFields: [
    {
      label: "Arrival Date",
      name: "arrivalDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "ATB",
      name: "berthDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "Sail Date",
      name: "sailDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "ETA Next Port",
      name: "etaNextPort",
      type: "date",
      isEdit: true,
    },
    {
      label: "Next Port",
      name: "nextPortId",
      type: "dropdown",
      labelType: "port",
      foreignTable: "name,tblPort",
      isEdit: true,
    },
    {
      label: "Last Port",
      name: "lastPortId",
      type: "dropdown",
      labelType: "port",
      foreignTable: "name,tblPort",
      isEdit: true,
    },
    {
      label: "Prior To Last Port",
      name: "priorToLastPortId",
      type: "dropdown",
      labelType: "port",
      foreignTable: "name,tblPort",
      isEdit: true,
    },
    {
      label: "Prior To Prior Port",
      name: "priorToPriorPortId",
      type: "dropdown",
      labelType: "port",
      foreignTable: "name,tblPort",
      isEdit: true,
    },
    {
      label: "SCR No",
      name: "scrNo",
      isEdit: true,
    },
    {
      label: "Empty Depot",
      name: "depotId",
      isEdit: true,
    },
  ],
  dateFields: [
    { label: "IGM No", name: "igmNo", type: "text", isEdit: true },
    {
      label: "IGM Date",
      name: "igmDate",
      type: "date",
      isEdit: true,
    },
    { label: "Rotation No", name: "rotationNo", type: "text", isEdit: true },
    {
      label: "Rotation Date",
      name: "rotationDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "PC NO",
      name: "pcNo",
      type: "text",
      isEdit: true,
    },
    {
      label: "PC Date",
      name: "pcDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "Via No",
      name: "viaNo",
      type: "text",
      isEdit: true,
    },
    {
      label: "Via Date",
      name: "viaDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "NO of Crew",
      name: "noOFCrew",
      type: "number",
      isEdit: true,
    },
    {
      label: "Light House Due",
      name: "lightHouseDues",
      isEdit: true,
    },
  ],
  consignorFields: [
    {
      label: "Passenger List",
      name: "passengerList",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
    {
      label: "Same Bottom Cargo",
      name: "sameBottomCargo",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
    {
      label: "Ship Store Declaration",
      name: "shipStoresDeclaration",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
    {
      label: "Crew List Declaration",
      name: "crewListDeclaration",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
    {
      label: "Maritime Declaration",
      name: "maritimeDeclaration",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
    {
      label: "Export Locking",
      name: "exportLocking",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
    {
      label: "Import Locking",
      name: "importLocking",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
  ],
  additionalFields: [
    {
      label: "Cargo Description",
      name: "cargoDescription",
      style: "sm:w-[min(100%,300px)]",
      multiline: true,
      rows: 1,
      type: "textarea",
      isEdit: true,
    },
    {
      label: "Auth. Person Pan No",
      name: "authPersonPanNo",
      isEdit: true,
    },
    {
      label: "Ships Store IRN",
      name: "shipsStoreIrn",
      isEdit: true,
    },
    {
      label: "Crew Effect IRN",
      name: "crewEffectIrn",
      isEdit: true,
    },
    {
      label: "Person Details IRN",
      name: "personDetailsIrn",
      isEdit: true,
    },
  ],
};

export default fieldData;
