const fieldData = {
  voyageFields: [
    {
      label: "Port Of Call",
      name: "portOfCallId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      foreignTable: "name,tblPort",
      joins: "JOIN tblMasterData m ON m.id = p.portTypeId",
      where: "m.name IN ('SEA PORT','INLAND PORT')",
      orderBy: "p.name",
      foreignTable: "name,tblPort",
      isEdit: true,
      required: true,
    },
    {
      label: "Vessel Name",
      name: "vesselId",
      type: "dropdown",
      tableName: "tblVessel",
      foreignTable: "name,tblVessel",
      displayColumn: "t.name",
      orderBy: "t.name",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblVessel",
      isEdit: true,
      required: true,
    },
    {
      label: "Voyage No",
      name: "voyageId",
      type: "dropdown",
      tableName: "tblVoyage t",
      displayColumn: "t.voyageNo",
      orderBy: "t.voyageNo",
      selectedConditions: [{ vesselId: "vesselId" }],
      foreignTable: "voyageNo,tblVoyage",
      isEdit: true,
      required: true,
    },
    {
      label: "Terminal",
      name: "berthId",
      type: "dropdown",
      tableName: "tblPort p",
      foreignTable: "name,tblPort",
      joins: "JOIN tblMasterData m ON m.id = p.portTypeId",
      where: "m.name IN ('PORT TERMINAL')",
      displayColumn: "p.name",
      orderBy: "p.name",
      selectedConditions: [{ portOfCallId: "referencePortId" }],
      isEdit: true,
      required: true,
    },
    {
      label: "Export Voyage No",
      name: "exportExchangeRate",
      type: "number",
      isEdit: true,
    },
    {
      label: "Import Voyage No",
      name: "importExchangeRate",
      type: "number",
      isEdit: true,
    },
    {
      label: "ETA",
      name: "eta",
      type: "date",
      isEdit: true,
    },
    {
      label: "ETD",
      name: "etd",
      type: "date",
      isEdit: true,
    },
    {
      label: "ETB",
      name: "etb",
      type: "date",
      isEdit: true,
    },
    {
      label: "Port Cut Off",
      name: "portCutoff",
      type: "date",
      isEdit: true,
    },

    {
      label: "Arrival Date",
      name: "arrivalDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "ATB",
      name: "berthDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "Sail Date",
      name: "sailDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "ETA Next Port",
      name: "etaNextPort",
      type: "date",
      isEdit: true,
    },
    {
      label: "Next Port",
      name: "nextPortId",
      type: "dropdown",
      tableName: "tblPort t",
      displayColumn: "t.name",
      foreignTable: "name,tblPort",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "Last Port",
      name: "lastPortId",
      type: "dropdown",
      tableName: "tblPort t",
      displayColumn: "t.name",
      foreignTable: "name,tblPort",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "Prior To Last Port",
      name: "priorToLastPortId",
      type: "dropdown",
      tableName: "tblPort t",
      foreignTable: "name,tblPort",
      displayColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "Prior To Prior Port",
      name: "priorToPriorPortId",
      type: "dropdown",
      tableName: "tblPort t",
      foreignTable: "name,tblPort",
      displayColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "SCR No",
      name: "scrNo",
      isEdit: true,
    },
    {
      label: "Empty Depot",
      name: "depotId",
      isEdit: true,
    },

    { label: "IGM No", name: "igmNo", type: "text", isEdit: true },
    {
      label: "IGM Date",
      name: "igmDate",
      type: "date",
      isEdit: true,
    },
    { label: "Rotation No", name: "rotationNo", type: "text", isEdit: true },
    {
      label: "Rotation Date",
      name: "rotationDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "PC No",
      name: "pcNo",
      type: "text",
      isEdit: true,
    },
    {
      label: "PC Date",
      name: "pcDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "Via No",
      name: "viaNo",
      type: "text",
      isEdit: true,
    },
    {
      label: "Via Date",
      name: "viaDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "No of Crew",
      name: "noOFCrew",
      type: "number",
      isEdit: true,
    },
    {
      label: "Light House Due",
      name: "lightHouseDues",
      isEdit: true,
    },

    {
      label: "Passenger List",
      name: "passengerList",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
    {
      label: "Same Bottom Cargo",
      name: "sameBottomCargo",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
    {
      label: "Ship Store Declaration",
      name: "shipStoresDeclaration",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
    {
      label: "Crew List Declaration",
      name: "crewListDeclaration",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
    {
      label: "Maritime Declaration",
      name: "maritimeDeclaration",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
    {
      label: "Export Locking",
      name: "exportLocking",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
    {
      label: "Import Locking",
      name: "importLocking",
      type: "radio",
      radioData: [
        { label: "Yes", value: "Y" },
        { label: "No", value: "N" },
      ],
      isEdit: true,
    },
    {
      label: "Auth Person Pan No",
      name: "authPersonPanNo",
      isEdit: true,
    },
    {
      label: "Cargo Description",
      name: "cargoDescription",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
    },
    {
      label: "Ships Store IRN",
      name: "shipsStoreIrn",
      isEdit: true,
    },
    {
      label: "Crew Effect IRN",
      name: "crewEffectIrn",
      isEdit: true,
    },
    {
      label: "Person Details IRN",
      name: "personDetailsIrn",
      isEdit: true,
    },
  ],
};

export const VoyageRoute = [
  { label: "Port of Call", value: "p.name" },
  { label: "Voyage No", value: "v.voyageId" },
  { label: "Vessel No", value: "ve.name" },
  { label: "IGM NO", value: "v.igmNo" },
  { label: "Export Locking", value: "v.exportLocking" },
  { label: "Import Locking", value: "v.importLocking" },
  { label: "Terminal", value: "p.name" },
  { label: "Voyage", value: "v.voyageNo" },
];

export default fieldData;
