import { getUserByCookies } from "@/utils";
import AddIcon from "@mui/icons-material/Add";
import CloseIcon from "@mui/icons-material/Close";

const userData = getUserByCookies();

export const fieldData = {
  doFields: [
    {
      label: "MBL No",
      name: "mblNo",
      isEdit: true,
      disabled: true,
    },
    {
      label: "MBL Date",
      name: "mblDate",
      type: "date",
      isEdit: true,
      disabled: true,
    },
    {
      label: "HBL No",
      name: "hblNo",
      isEdit: true,
      disabled: true,
    },
    {
      label: "HBL Date",
      name: "hblDate",
      type: "date",
      isEdit: true,
      disabled: true,
    },
    {
      label: "PLR",
      name: "plrId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      joins:
        "JOIN tblMasterData m ON m.id = p.portTypeId JOIN tblCountry c ON c.id = p.countryId",
      where: "m.name IN ('SEA PORT','INLAND PORT')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "POL",
      name: "polId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      joins:
        "JOIN tblMasterData m ON m.id = p.portTypeId JOIN tblCountry c ON c.id = p.countryId",
      where: "m.name IN ('SEA PORT','INLAND PORT')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "POD",
      name: "podId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      joins: "JOIN tblMasterData m ON m.id = p.portTypeId",
      where: "m.name IN ('SEA PORT','INLAND PORT')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "FPD",
      name: "fpdId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      joins: "JOIN tblMasterData m ON m.id = p.portTypeId",
      where: "m.name IN ('SEA PORT','INLAND PORT')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "Consignee",
      name: "consigneeText",
      isEdit: true,
    },
    {
      label: "HSS",
      name: "hss",
      isEdit: true,
      type: "radio",
      radioData: [
        { label: "Yes", value: true },
        { label: "No", value: false },
      ],
    },
    {
      label: "Clearing Agent",
      name: "customBrokerText",
      isEdit: true,
    },
    {
      label: "Depot",
      name: "emptyDepotId",
      isEdit: true,
      type: "dropdown",
      displayColumn: "p.name",
      tableName: "tblPort p",
      joins: `join tblMasterData m on m.id = p.portTypeId and m.name = 'DEPOT' and m.masterListName = 'tblPortType' and p.status = 1`,
      where: `p.companyId = ${userData?.companyId}`,
      orderBy: "p.name",
      foreignTable: "name,tblPort",
    },
    {
      label: "Vessel",
      name: "podVesselId",
      type: "dropdown",
      displayColumn: "t.name",
      searchColumn: "t.name",
      tableName: "tblVessel t",
      joins: `left join tblLocation l on l.id = ${userData?.location} left JOIN tblVoyageRoute vr ON vr.vesselId = t.id left join tblPort p on p.id = vr.portOfCallId `,
      where: ` GETDATE() >= vr.gateOpenLine AND GETDATE() < vr.gateCloseLine and p.name = l.name `,
      orderBy: "t.name",
      foreignTable: "name,tblVessel",
      changeFun: "handleDropdownChange",
      isEdit: true,
      disabled: true,
    },
    {
      label: "Voyage",
      name: "podVoyageId",
      type: "dropdown",
      tableName: "tblVoyage vo",
      idColumn: "id",
      displayColumn: "vo.voyageNo",
      searchColumn: "vo.voyageNo",
      selectedConditions: [{ podVesselId: "vo.vesselId" }],
      joins: `join tblVoyageRoute vr on vr.voyageId = vo.id`,
      where: `GETDATE() >= vr.gateOpenLine AND GETDATE() < vr.gateCloseLine and vo.companyid = ${userData?.companyId} and vo.status = 1`,
      orderBy: "vo.voyageNo",
      foreignTable: "voyageNo,tblVoyage",
      isEdit: true,
      disabled: true,
    },
    {
      label: "Surveyor Name",
      name: "surveyorId",
      isEdit: true,
    },
    {
      label: "DO Date",
      name: "doDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "DO Validity Date",
      name: "doValidDate",
      type: "date",
      isEdit: true,
    },
  ],

  tblBlContainer: [
    {
      label: "Select For DO",
      name: "selectForDO",
      type: "checkbox",
      isEdit: true,
    },
    {
      label: "CONTAINER NO",
      name: "containerNo",
      isEdit: true,
      required: true,
      disabled: true,
    },
    {
      label: "Size",
      name: "sizeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblSize'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
      changeFun: "setISOBySize",
      disabled: true,
    },
    {
      label: "Type",
      name: "typeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblType'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      isEdit: true,
      changeFun: "setISOByType",
      disabled: true,
    },
    {
      label: " Valid Till",
      name: "doValidityDate",
      type: "date",
      isEdit: true,
    },
  ],
};
export const cfsGridButtons = [
  { text: "Add", icon: <AddIcon />, func: "gridAddHandler" },
  { text: "Delete", icon: <CloseIcon />, func: "gridDeleteHandler" },
];

export const advanceSearchFields = {
  bl: [
    {
      label: "BL No",
      name: "blNo",
      isEdit: true,
    },
  ],
};
