const fieldData = {
  smtpFields: [
    {
      label: "Code",
      name: "code",
      isEdit: "true",
      required: true,
    },
    {
      label: "Name",
      name: "name",
      isEdit: "true",
      required: true,
    },
    {
      label: "Country Name",
      name: "countryId",
      type: "dropdown",
      tableName: "tblCountry t",
      displayColumn: "t.name",
      foreignTable: "name,tblCountry",
      orderBy: "t.name",
      isEdit: true,
      required: true,
    },
    {
      label: "State/Region",
      name: "stateId",
      type: "dropdown",
      tableName: "tblState t",
      displayColumn: "t.name",
      foreignTable: "name,tblState",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "City Name",
      name: "cityId",
      type: "dropdown",
      tableName: "tblCity t",
      displayColumn: "t.name",
      foreignTable: "name,tblCity",
      selectedConditions: ["countryId"],
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "Company Address",
      name: "address",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: "true",
      required: true,
    },
    {
      label: "Zip Code",
      name: "pincode",
      isEdit: "true",
    },
    {
      label: "Phone",
      name: "telephoneNo",
      type: "number",
      isEdit: "true",
    },
    {
      label: "Email ID",
      name: "emailId",
      isEdit: "true",
    },
    {
      label: "Pan No",
      name: "panNo",
      isEdit: "true",
    },
    {
      label: "Remarks",
      name: "remarks",
      multiline: true,
      rows: 1,
      type: "textarea",
      isEdit: true,
      isEdit: "true",
    },
    {
      label: "GSTIN No",
      name: "taxRegistrationNo",
      isEdit: "true",
    },
    {
      label: "Company Group Name",
      name: "companyGroupId",
      type: "dropdown",
      tableName: "tblMasterData m",
      foreignTable: "name,tblMasterData",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblCompanyGroup'",
      orderBy: "m.name",
      isEdit: true,
    },
    {
      label: "Credit Period",
      name: "creditPeriod",
      type: "number",
      isEdit: "true",
    },
    {
      label: "Currency",
      name: "currencyId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      foreignTable: "name,tblMasterData",
      where: "m.masterListName = 'tblCurrency'",
      orderBy: "m.name",
      isEdit: true,
    },
    {
      label: "IEC No",
      name: "importExportCode",
      isEdit: "true",
    },
    {
      label: "Website",
      name: "website",
      isEdit: "true",
    },
  ],
};

export const SmtpCarrier = [
  { label: "Code", value: "co.code" },
  { label: "Name", value: "co.name" },
  { label: "Country Name", value: "c.name" },
  { label: "State Name", value: "s.name" },
  { label: "City Name", value: "ci.name" },
  { label: "Phone No", value: "co.telephoneNo" },
  { label: "Email Id", value: "co.emailId " },
  { label: "Pan No", value: "co.panNo " },
  { label: "GSTIN No", value: "co.taxRegistrationNo" },
];

export default fieldData;
