const fieldData = {
  voyageFields: [
    {
      label: "Voyage NO",
      name: "voyageNo",
      isEdit: "true",
      required: true,
    },
    {
      label: "Vessel Name",
      name: "vesselId",
      type: "dropdown",
      tableName: "tblVessel",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblVessel",
      isEdit: true,
      required: true,
    },
    {
      label: "Master",
      name: "masterName",
      isEdit: "true",
    },
    {
      label: " Master Nationality",
      name: "masterNationalityId",
      type: "dropdown",
      tableName: "tblCountry",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCountry",
      isEdit: true,
      required: true,
    },
    // coomented out
    // {
    //   label: "Company",
    //   name: "companyId",
    //   type: "dropdown",
    //   tableName: "tblCompany t",
    //   displayColumn: "t.name",
    //   searchColumn: "t.name",
    //   orderBy: "t.name",
    //   foreignTable: "name,tblCompany",
    //   required: true,
    //   isEdit: true,
    // },
    // {
    //   label: "Company Branch",
    //   name: "companyBranchId",
    //   type: "dropdown",
    //   tableName: "tblCompanyBranch t",
    //   displayColumn: "t.name",
    //   orderBy: "t.name",
    //   foreignTable: "name,tblCompanyBranch",
    //   selectedConditions: [{ companyId: "companyId" }],
    //   required: true,
    //   isEdit: true,
    // },
    {
      label: "Dc no",
      name: "masterIdNo",
      isEdit: "true",
    },
    {
      label: "Convey Reference no",
      name: "conveyRefNo",
      isEdit: "true",
    },
    {
      label: "Cargo Desc Code",
      name: "cargoDescCodeId",
      type: "dropdown",
      tableName: "tblMasterData",
      displayColumn: "t.name",
      where: "masterListName = 'tblCargoDesc'",
      orderBy: "t.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
    {
      label: "Purpose of Call",
      name:"purposeOfCall",
      isEdit: "true",
      type:"number",
    },
  ],
};

export const voyage = [
  { label: "Vessel Name", value: "v1.name" },
  { label: "Voyage No", value: "v.voyageNo" },
];
export default fieldData;
