const fieldData = {
  invoiceConversionFields: [
    {
      label: "Location",
      name: "port",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "Vessel",
      name: "vessel",
      type: "dropdown",
      tableName: "tblVessel t",
      idColumn: "id",
      displayColumn: "t.name",
      searchColumn: "t.name",
      orderBy: "t.name",
      isEdit: true,
    },
    {
      label: "Voyage",
      name: "voyage",
      type: "dropdown",
      tableName: "tblVoyage t",
      idColumn: "id",
      displayColumn: "t.voyageNo",
      searchColumn: "t.voyageNo",
      selectedConditions: [{ vessel: "vesselId" }],
      orderBy: "t.voyageNo",
      isEdit: true,
    },
    {
      label: "From Date",
      name: "fromDate",
      type: "date",
      isEdit: true,
    },
    {
      label: " Date ",
      name: "toDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "CFS/ICD",
      name: "nominatedAreaId",
      type: "dropdown",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      tableName: "tblPort p",
      joins: "left join tblMasterData m on m.id = p.portTypeId",
      where: "m.code = 'CFS'",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      style: "col-span-3 row-span-1",
      isEdit: true,
    },
    
  ],
};
export default fieldData;
export const metaData = [];
