import { getUserByCookies } from "@/utils";
import AddIcon from "@mui/icons-material/Add";
import CloseIcon from "@mui/icons-material/Close";
import FileCopyIcon from "@mui/icons-material/FileCopy";
import UploadFileIcon from "@mui/icons-material/UploadFile";

const userData = getUserByCookies();

export const fieldData = {
  mblFields: [
    {
      label: "Line No/Sub Line No",
      name: "itemNo",
      isEdit: true,
    },
    {
      label: "Liner",
      name: "shippingLineId",
      type: "dropdown",
      tableName: "tblCompany t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCompany",
      required: true,
      isEdit: true,
      disabled: true,
    },
    // {
    //   label: "Company",
    //   name: "companyId",
    //   type: "dropdown",
    //   tableName: "tblCompany t",
    //   displayColumn: "t.name",
    //   orderBy: "t.name",
    //   foreignTable: "name,tblCompany",
    //   required: true,
    //   isEdit: true,
    //   disabled: true,
    // },
    // {
    //   label: "Company Branch",
    //   name: "companyBranchId",
    //   type: "dropdown",
    //   tableName: "tblCompanyBranch t",
    //   displayColumn: "t.name",
    //   orderBy: "t.name",
    //   foreignTable: "name,tblCompanyBranch",
    //   isEdit: true,
    //   required: true,
    //   disabled: true,
    // },
    {
      label: "MBL No",
      name: "mblNo",
      isEdit: true,
      required: true,
    },
    {
      label: "MBL Date",
      name: "mblDate",
      type: "date",
      isEdit: true,
      required: true,
    },
    {
      label: "BLStatus",
      name: "blStatus",
      type: "radio",
      radioData: [
        { label: "Draft", value: "D" },
        { label: "Final", value: "F" },
      ],
      isEdit: true,
    },
    // {
    //   label: "BL Type",
    //   name: "blTypeId",
    //   type: "dropdown",
    //   tableName: "tblMasterData m",
    //   displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
    //   where: "m.masterListName = 'tblBlIssueType'",
    //   orderBy: "m.name",
    //   foreignTable: "code-name,tblMasterData",
    //   isEdit: true,
    // },
    {
      label: "Vessel",
      name: "podVesselId",
      type: "dropdown",
      tableName: "tblVessel t",
      idColumn: "id",
      displayColumn: "t.name",
      searchColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblVessel",
      changeFun: "handleChangeOnVessel",
      isEdit: true,
    },
    {
      label: "Voyage",
      name: "podVoyageId",
      type: "dropdown",
      tableName: "tblVoyage t",
      idColumn: "id",
      displayColumn: "t.voyageNo",
      searchColumn: "t.voyageNo",
      selectedConditions: [{ podVesselId: "vesselId" }],
      orderBy: "t.voyageNo",
      foreignTable: "voyageNo,tblVoyage",
      isEdit: true,
    },

    // {
    //   label: "Container Status",
    //   name: "containerStatusId",
    //   type: "dropdown",
    //   tableName: "tblMasterData m",
    //   displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
    //   where: "m.masterListName = 'tblContainerStatus'",
    //   orderBy: "m.name",
    //   foreignTable: "code-name,tblMasterData",
    //   isEdit: true,
    //   required: true,
    // },
  ],
  csnFields: [
    // {
    //   label: "Sender Id",
    //   name: "senderId",
    //   isEdit: true,
    // },
    // {
    //   label: "Receive Id",
    //   name: "receiveId",
    //   isEdit: true,
    // },
    // {
    //   label: "Vessel Id Type",
    //   name: "vesselIdType",
    //   type: "dropdown",
    //   // tableName: "tblVessel t",
    //   // displayColumn: "t.name",
    //   // orderBy: "t.name",
    //   // foreignTable: "name,tblVessel",
    //   // required: true,
    //   isEdit: true,
    // },
    // {
    //   label: "Vessel No",
    //   name: "vesselNo",
    //   isEdit: true,
    // },
    // {
    //   label: "Submit Type",
    //   name: "submitType",
    //   type: "dropdown",
    //   tableName: "tblMasterData m",
    //   displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
    //   where: "m.masterListName = 'tblSubmitterType'",
    //   orderBy: "m.name",
    //   foreignTable: "code-name,tblMasterData",
    //   isEdit: true,
    // },
    // {
    //   label: "Code",
    //   name: "code",
    //   isEdit: true,
    // },
    // {
    //   label: "Auth.Person Code",
    //   name: "authPersonCode",
    //   isEdit: true,
    // },
    // {
    //   label: "VCN No",
    //   name: "vcnNo",
    //   isEdit: true,
    // },
    // {
    //   label: "CSN No",
    //   name: "csnNo",
    //   isEdit: true,
    // },
    // {
    //   label: "CSN Date",
    //   name: "csnDate",
    //   type: "date",
    //   isEdit: true,
    // },
    {
      label: "CIN Type",
      name: "cinType",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      searchColumn: "m.name",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      where: "m.masterListName = 'tblCINType'",
      isEdit: true,
    },
    {
      label: "CIN NO",
      name: "cinNo",
      isEdit: true,
    },
    {
      label: "CSN No",
      name: "csnNo",
      isEdit: true,
    },
    {
      label: "CSN Date",
      name: "csnDate",
      type: "date",
      isEdit: true,
    },
  ],
  routeDetails: [
    {
      label: "Port of Acceptance",
      name: "plrId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "Port of Loading",
      name: "polId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
      required: true,
      changeFun: "handleChangeOnPOL",
    },
    {
      label: "Transhipment Port 1",
      name: "transhipPort1Id",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "Transhipment Port 2",
      name: "transhipPort2Id",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "Transhipment Port 3",
      name: "transhipPort3Id",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "Port of Unloading",
      name: "podId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
      changeFun: "handleChangeOnPOL",
    },
    {
      label: "Port of Destination",
      name: "fpdId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "ISNULL(p.code,'') + ' - ' + ISNULL(p.name,'')",
      orderBy: "p.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
      required: true,
      changeFun: "handleChangeOnPOL",
    },
    {
      label: "CFS",
      name: "nominatedAreaId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      joins:
        `join tblMasterData m on m.id = p.portTypeId  and m.masterListName = 'tblPortType' and m.code = 'CFS' and p.companyId = ${userData?.companyId}`,
      isEdit: true,
      foreignTable: "name,tblPort",
    },
    {
      label: "Direct Port Delivery",
      name: "dpdId",
      type: "dropdown",
      tableName: "tblPort t",
      displayColumn: "ISNULL(t.code,'') + ' - ' + ISNULL(t.name,'')",
      joins: "JOIN tblMasterData m ON m.id = t.portTypeId",
      where: "m.masterListName = 'tblPortType' AND m.code = 'DPD'",
      orderBy: "t.name",
      foreignTable: "code-name,tblPort",
      isEdit: true,
    },
    {
      label: "Type of Cargo",
      name: "cargoTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.code",
      where: "m.masterListName = 'tblServiceType' and status  =  1",
      foreignTable: "code,tblMasterData",
      orderBy: "m.name",
      isEdit: true,
    },
    {
      label: "Cargo Movement",
      name: "movementTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.code",
      where: "m.masterListName = 'tblMovementType'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
    {
      label: "Movement Carrier",
      name: "movementCarrierId",
      type: "dropdown",
      tableName: "tblCarrierPort t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCarrierPort",
      isEdit: true,
      changeFun: "setCarrierBondAndCode",
    },
    {
      label: "Transit Bond No",
      name: "carrierBondNo",
      disabled: true,
    },
    {
      label: "Carrier Code",
      name: "carrierPanNo",
      disabled: true,
    },
    {
      label: "Post Carriage",
      name: "postCarriageId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblMode'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
  ],
  hblBottomFields: [
    {
      label: "Item Type",
      name: "blTypeId",
      type: "dropdown",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      tableName: "tblMasterData m",
      where: "m.masterListName = 'tblItemType'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      isEdit: true,
    },
    {
      label: "Nature of Cargo",
      name: "natureOfCargoId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      searchColumn: "m.name",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      where: "m.masterListName = 'tblTypeOfShipment'",
      isEdit: true,
    },
    {
      label: "MLO Code",
      name: "mloId",
      type: "dropdown",
      tableName: "tblCompany t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCompany",
      required: true,
      isEdit: true,
    },
    {
      label: "Cargo Gross Wt(Kgs)",
      name: "grossWt",
      type: "number",
      // required: true,
      isEdit: true,
      disabled: true,
    },

    {
      label: "Net Wt(Kgs)",
      name: "netWt",
      type: "number",
      // required: true,
      disabled: true,
      isEdit: true,
    },
    {
      label: "Package Type",
      name: "packageId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblPackage'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      required: true,
      // isEdit: true,
      disabled: true,
    },
    {
      label: "No of Package",
      name: "noOfPackages",
      type: "number",
      isEdit: true,
      // required: true,
      disabled: true,
    },
    {
      label: "UNO Code",
      name: "unNo",
      type: "text",
      isEdit: true,
      blurFun: "validUnoImoCode",
    },
    {
      label: "IMO Code",
      name: "imoCode",
      type: "text",
      isEdit: true,
      blurFun: "validUnoImoCode",
    },

    {
      label: "Invoice Value",
      name: "invoiceNo",
      isEdit: true,
    },
    {
      label: "Currency",
      name: "demurrageCurrencyId",
      type: "dropdown",
      tableName: "tblMasterData m",
      foreignTable: "code,tblMasterData",
      displayColumn: "m.code",
      where: "m.masterListName = 'tblCurrency'",
      isEdit: true,
    },
    {
      label: "Marks & Numbers",
      name: "marksNos",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
      required: true,
    },
    {
      label: "Good & Description",
      name: "goodsDesc",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
      required: true,
    },
  ],
  transitFields: [
    {
      label: "Transit Bond No",
      name: "transitBondNo",
      isEdit: true,
    },
    {
      label: "Carrier Code",
      name: "carrierCode",
      isEdit: true,
    },
  ],
  consignorFields: [
    {
      label: "Name",
      name: "shipperText",
      required: true,
      isEdit: true,
    },
    {
      label: "Type",
      name: "shipperTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblIdentificationType'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
    {
      label: "Code",
      name: "shipperIdNo",
      isEdit: true,
    },
    {
      label: "City",
      name: "shipperCity",
      type: "dropdown",
      tableName: "tblCity t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCity",
      required: true,
      isEdit: true,
      changeFun: "setCountryAndState",
    },
    {
      label: "Country",
      name: "shipperCountry",
      type: "dropdown",
      tableName: "tblCountry t",
      displayColumn: "ISNULL(t.code,'') + ' - ' + ISNULL(t.name,'')",
      orderBy: "t.name",
      foreignTable: "code-name,tblCountry",
      required: true,
      isEdit: true,
    },
    // {
    //   label: "Post Code",
    //   name: "consignorPostCode",
    //   isEdit: true,
    // },
    {
      label: "Address",
      name: "shipperAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      required: true,
      isEdit: true,
    },
  ],
  consigneeFields: [
    {
      label: "Name",
      name: "consigneeText",
      isEdit: true,
      required: true,
    },
    {
      label: "Type",
      name: "consigneeTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblIdentificationType'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
    { label: "Code", name: "consigneeIdNo", isEdit: true },
    {
      label: "City",
      name: "consigneeCity",
      type: "dropdown",
      tableName: "tblCity t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCity",
      isEdit: true,
      required: true,
      changeFun: "setCountryAndState",
    },
    {
      label: "State",
      name: "consigneeState",
      type: "dropdown",
      tableName: "tblState t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblState",
      isEdit: true,
    },
    {
      label: "Country",
      name: "consigneeCountry",
      type: "dropdown",
      tableName: "tblCountry t",
      displayColumn: "ISNULL(t.code,'') + ' - ' + ISNULL(t.name,'')",
      orderBy: "t.name",
      foreignTable: "code-name,tblCountry",
      isEdit: true,
      required: true,
    },
    // { label: "GSTIN", name: "consigneeGSTIN", isEdit: true },
    // { label: "IEC", name: "consigneeIdNo", required: true, isEdit: true },
    // {
    //   label: "Email Id",
    //   name: "emailTo",
    //   required: true,
    //   isEdit: true,
    // },
    {
      label: "Post Code",
      name: "consigneePinCode",
      type: "number",
      isEdit: true,
      blurFun: "checkPinCode",
    },
    {
      label: "Email Id",
      name: "emailTo",
      isEdit: true,
    },
    {
      label: "Address",
      name: "consigneeAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
      required: true,
    },
  ],
  notifyFields: [
    {
      label: "Name",
      name: "notifyPartyText",
      isEdit: true,
      required: true,
    },
    {
      label: "PAN Number",
      name: "notifyParty1IdNo",
      isEdit: true,
      blurFun: "panCardValid",
    },
    {
      label: "City",
      name: "notifyParty1City",
      type: "dropdown",
      tableName: "tblCity t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCity",
      isEdit: true,
      required: true,
      changeFun: "setCountryAndState",
    },
    {
      label: "State",
      name: "notifyParty1State",
      type: "dropdown",
      tableName: "tblState t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblState",
      isEdit: true,
    },
    {
      label: "Country",
      name: "notifyParty1Country",
      type: "dropdown",
      tableName: "tblCountry t",
      displayColumn: "ISNULL(t.code,'') + ' - ' + ISNULL(t.name,'')",
      orderBy: "t.name",
      foreignTable: "code-name,tblCountry",
      isEdit: true,
      required: true,
    },
    {
      label: "Post Code",
      name: "notifyParty1PinCode",
      type: "number",
      isEdit: true,
      blurFun: "checkPinCode",
    },
    {
      label: "Email Id",
      name: "emailCC",
      isEdit: true,
    },
    {
      label: "Address",
      name: "notifyPartyAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
      required: true,
    },
  ],
  tgBondDetails: [
    {
      label: "TG Carrier",
      name: "tgCarrierId",
      type: "dropdown",
      isEdit: true,
    },
    {
      label: "TG Bond No",
      name: "tgBondNo",
      isEdit: true,
    },
    {
      label: "TG Carrier Code",
      name: "tgCarrierCode",
      isEdit: true,
    },
  ],
  tblBlContainer: [
    {
      label: "CONTAINER NO",
      name: "containerNo",
      isEdit: true,
      required: true,
      blurFun: "containerNumberHandler",
    },
    {
      label: "Size",
      name: "sizeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblSize'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
      changeFun: "setISOBySize",
    },
    {
      label: "Type",
      name: "typeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblType'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      isEdit: true,
      changeFun: "setISOByType",
    },
    {
      label: "ISO Code",
      name: "isoCode",
      type: "dropdown",
      tableName: "tblIsocode m",
      displayColumn: "m.isocode",
      foreignTable: "isocode,tblIsocode",
      isEdit: true,
      required: true,
    },
    {
      label: "Status",
      name: "containerStatusId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblContainerStatus'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
    {
      label: "Seal Type",
      name: "sealTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblSealType'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      isEdit: true,
    },
    // { label: "Seal No.", name: "agentSealNo", isEdit: true },
    {
      label: "SOC Flag",
      name: "soc",
      isEdit: true,
      type: "checkbox",
      // required: true,
    },
    // {
    //   label: "Custom Seal",
    //   // name: "containerAgentCode",
    //   isEdit: true,
    //   // required: true,
    // },
    // {
    //   label: "Agent Seal",
    //   // name: "containerAgentCode",
    //   isEdit: true,
    //   // required: true,
    // },
    {
      label: "Custom Seal",
      name: "customSealNo",
      isEdit: true,
      // required: true,
    },
    {
      label: "Agent Seal",
      name: "agentSealNo",
      isEdit: true,
      // required: true,
    },

    {
      label: "Container Agent Code",
      name: "containerAgentCode",
      isEdit: true,
      required: true,
      blurFun: "panCardValid",
    },
    {
      label: "Cargo Gross Wt(Kgs)",
      name: "grossWt",
      type: "number",
      isEdit: true,
      required: true,
    },

    // {
    //   label: "Cargo net Wt(Kgs)",
    //   name: "netwt",
    //   type: "number",
    //   isEdit: true,
    //   required: true,
    // },
    { label: "NetWt(Kgs)", name: "netWt", type: "number", isEdit: true },
    { label: "Volume(CBM)", name: "volume", isEdit: true },
    {
      label: "NO of Package",
      name: "noOfPackages",
      type: "number",
      isEdit: true,
      required: true,
    },
    {
      label: "Package Type",
      name: "packageId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblPackage'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      required: true,
      isEdit: true,
    },

    {
      label: "UNO Code",
      name: "unNo",
      type: "text",
      isEdit: true,
      blurFun: "validUnoImoCode",
    },
    {
      label: "IMO Code",
      name: "imoCode",
      type: "text",
      isEdit: true,
      blurFun: "validUnoImoCode",
    },
    {
      label: "Reefer Temp",
      name: "refTemp",
      type: "number",
      isEdit: true,
      acceptBelowZero: true,
    },
    {
      label: "Reefer Temp Unit",
      name: "refTempUnitId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where:
        "m.groupId in (select id from tblMasterData where name = 'TEMPERATURE')",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      isEdit: true,
    },

    {
      label: "OGG Front",
      name: "oogFront",
      isEdit: true,
    },
    {
      label: "OGG Back",
      name: "oogBack",
      isEdit: true,
    },
    {
      label: "OGG Back Left",
      name: "oogBackLeft",
      isEdit: true,
    },
    {
      label: "OGG Right",
      name: "oogRight",
      isEdit: true,
    },
    {
      label: "OGG Top",
      name: "oogTop",
      isEdit: true,
    },
    {
      label: "Dimensions",
      name: "dimensionUnitId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where:
        "m.groupId in (select id from tblMasterData where name = 'LENGTH')",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      isEdit: true,
    },
  ],
  tblBlPackingList: [
    { label: "HS No", name: "hsnCode", isEdit: true },
    { label: "Cargo Item Description", name: "commodity", isEdit: true },
    // {
    //   label: "UNO Code",
    //   name: "imoId",
    //   type: "dropdown",
    //   labelType: "uno",
    //   isEdit: true,
    // },
    {
      label: "UNO Code",
      name: "unNo",
      type: "text",
      isEdit: true,
      blurFun: "validUnoImoCode",
    },
    {
      label: "IMO Code",
      name: "imoCode",
      type: "text",
      isEdit: true,
      blurFun: "validUnoImoCode",
    },
    {
      label: "No of Packages",
      name: "noOfPackages",
      type: "number",
      isEdit: true,
    },
    {
      label: "Package Type",
      name: "packageId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblPackage'",
      orderBy: "m.name",
      foreignTable: "code-name,tblMasterData",
      required: true,
      isEdit: true,
    },
  ],
  attachmentFields: [
    {
      name: "attachment",
      type: "fileupload",
      isEdit: true,
      dragDrop: true,
    },
  ],
};

export const totalFieldData = {
  totalFields: [
    { label: "Total Gross Wt(Kgs)", name: "grossWt" },
    { label: "Total No of Packages", name: "packages" },
  ],
};

export const mappingConsigneeToNotify = {
  notifyPartyText: "consigneeText",
  notifyParty1IdNo: "consigneeIdNo",
  // notifyPartyTypeId: "consigneeTypeId",
  notifyParty1Country: "consigneeCountry",
  notifyParty1State: "consigneeState",
  notifyParty1City: "consigneeCity",
  notifyParty1PinCode: "consigneePinCode",
  notifyPartyAddress: "consigneeAddress",
  emailCC: "emailTo",
};
export const mappingConsigneeToNotifyNoPan = {
  notifyPartyText: "consigneeText",
  // ❌ no notifyParty1IdNo here
  notifyParty1Country: "consigneeCountry",
  notifyParty1State: "consigneeState",
  notifyParty1City: "consigneeCity",
  notifyParty1PinCode: "consigneePinCode",
  notifyPartyAddress: "consigneeAddress",
  emailCC: "emailTo",
};

export const advanceSearchFields = {
  bl: [
    {
      label: "BL No",
      name: "blNo",
      isEdit: true,
    },
    {
      label: "MBL Date",
      name: "mblDate",
      type: "date",
      isEdit: true,
    },
  ],
};

export const gridButtons = [
  {
    text: "Add Row",
    icon: <AddIcon />,
    func: "gridAddHandler",
  },
  {
    text: "Delete Row",
    icon: <CloseIcon />,
    func: "gridDeleteHandler",
  },
  {
    text: "Copy Row",
    icon: <FileCopyIcon />,
    func: "gridCopyHandler",
  },
  {
    text: "Import Excel",
    icon: <UploadFileIcon />,
    func: "excelUpload",
  },
];
