import AddIcon from "@mui/icons-material/Add";
import CloseIcon from "@mui/icons-material/Close";
import FileCopyIcon from "@mui/icons-material/FileCopy";
import UploadFileIcon from "@mui/icons-material/UploadFile";

export const fieldData = {
  mblFields: [
    {
      label: "Line No/Sub Line No",
      name: "lineNo",
      isEdit: true,
    },
    {
      label: "Location(POD)",
      name: "podId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      joins: "JOIN tblMasterData m ON m.id = p.portTypeId JOIN tblCountry c ON c.id = p.countryId",
      where: "m.name = 'SEA PORT' AND c.name = 'India'",
      orderBy: "p.name",
      isEdit: true,
      required: true
    },
    {
      label: "Liner",
      name: "blOfId",
      type: "dropdown",
      tableName: "tblCompany t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCompany",
      required: true,
      isEdit: true
    },
    {
      label: "MBL No",
      name: "mblNo",
      isEdit: true,
      required: true,
    },
    {
      label: "MBL Date",
      name: "mblDate",
      type: "date",
      isEdit: true,
      required: true,
    },
    {
      label: "BLStatus",
      name: "blStatus",
      type: "radio",
      radioData: [
        { label: "Draft", value: "D" },
        { label: "Final", value: "F" },
      ],
      isEdit: true,
    },
    {
      label: "BL Type",
      name: "blTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblBlIssueType'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true
    },
    {
      label: "Vessel-Voyage No.",
      name: "podvesselId",
      type: "dropdown",
      tableName: "tblVoyage v",
      idColumn: "id",
      displayColumn: "ISNULL(ve.name,'') + ' - ' + ISNULL(v.voyageNo,'')",
      joins: "JOIN tblVessel ve ON ve.id = v.vesselId",
      searchColumn: "ve.name, v.voyageNo",
      orderBy: "ve.name, v.voyageNo",
      isEdit: true,
      required: true
    },
    // {
    //   label: "Manifest Vessel-Voyage",
    //   name: "podVesselId",
    //   type: "dropdown",
    //   labelType: "vessel",
    //   isEdit: true,
    // },
    {
      label: "Type of Cargo",
      name: "cargoTypeId",
      type: "dropdown",
      // tableName: "tblMasterData m",
      // foreignTable: "name,tblMasterData",
      // displayColumn: "m.name",
      // where: "m.masterListName = 'tblCargoType'",
      orderBy: "m.name",
      isEdit: true
    },
    {
      label: "Container Status",
      name: "containerStatusId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblContainerStatus'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
      required: true
    },
    // {
    //   label: "Mobile(Requester)",
    //   name: "mobileNo",
    //   type: "number",
    //   required: true,
    //   isEdit: true,
    // },

    // {
    //   label: "CIN Type",
    //   name: "cinType",
    //   type: "dropdown",
    //   labelType: "name,tblCINType",
    //   foreignTable: "name,tblMasterData",
    //   isEdit: true,
    // },
    // {
    //   label: "CIN No",
    //   name: "cinNo",
    //   isEdit: true,
    // },

    // {
    //   label: "Voyage Number",
    //   name: "podVoyageId",
    //   type: "number",
    //   isEdit: true,
    // },
    // {
    //   label: "Liner/FF Pan",
    //   name: "linerFFPan",
    //   type: "dropdown",
    //   labelType: "name,tblSubmitterType",
    //   foreignTable: "name,tblMasterData",
    //   isEdit: true,
    // },
    // {
    //   label: "Liner/FF Pan",
    //   name: "linerFfFPan",
    //   isEdit: true,
    // },
    // {
    //   label: "IGM No",
    //   name: "igmNo",
    //   type: "number",
    //   isEdit: true,
    //   required: true,
    // },
    // {
    //   label: "IGM Date",
    //   name: "igmDate",
    //   type: "date",
    //   isEdit: true,
    //   required: true,
    // },
    // {
    //   label: "Status",
    //   name: "statusId",
    //   type: "dropdown",
    //   labelType: "container",
    //   foreignTable: "name,tblMasterData",
    //   required: true,
    //   isEdit: true,
    // },
    // {
    //   label: "Rejection Remarks",
    //   name: "remarks",
    //   type: "textarea",
    //   rows: 2,
    //   gridColumn: "col-span-2 row-span-1 ",
    //   isEdit: true,
    //   required: true,
    // },
    // {
    //   label: "Company",
    //   name: "companyId",
    //   type: "dropdown",
    //   tableName: "tblCompany t",
    //   displayColumn: "t.name",
    //   orderBy: "t.name",
    //   foreignTable: "name,tblCompany",
    //   isEdit: true,
    //   required: true
    // },
    // {
    //   label: "Company Branch",
    //   name: "companyBranchId",
    //   type: "dropdown",
    //   tableName: "tblCompanyBranch t",
    //   displayColumn: "t.name",
    //   orderBy: "t.name",
    //   foreignTable: "name,tblCompanyBranch",
    //   isEdit: true,
    //   required: true
    // },

  ],
  csnFields: [
    {
      label: "Sender Id",
      name: "senderId",
      isEdit: true,
      required: true,
    },
    {
      label: "Receive Id",
      name: "receiveId",
      isEdit: true,
      required: true,
    },
    {
      label: "Vessel Id Type",
      name: "vesselIdType",
      type: "dropdown",
      // tableName: "tblVessel t",
      // displayColumn: "t.name",
      // orderBy: "t.name",
      // foreignTable: "name,tblVessel",
      required: true,
      isEdit: true
    },
    {
      label: "Vessel No",
      name: "vesselNo",
      isEdit: true,
      required: true,
    },
    {
      label: "Submit Type",
      name: "submitType",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblSubmitterType'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
      required: true
    },
    {
      label: "Code",
      name: "code",
      isEdit: true,
      required: true,
    },
    {
      label: "Auth.Person Code",
      name: "authPersonCode",
      isEdit: true,
      required: true,
    },
    {
      label: "VCN No",
      name: "vcnNo",
      isEdit: true,
      required: true,
    },
    {
      label: "CSN No",
      name: "csnNo",
      isEdit: true,
    },
    {
      label: "CSN Date",
      name: "csnDate",
      type: "date",
      isEdit: true,
    },
  ],
  routeDetails: [
    {
      label: "Port of Acceptance",
      name: "plrId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      orderBy: "p.name",
      foreignTable: "name,tblPort",
      isEdit: true
    },
    {
      label: "Port of Loading",
      name: "polId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      orderBy: "p.name",
      foreignTable: "name,tblPort",
      isEdit: true,
      required: true,
    },
    {
      label: "Transhipment Port 1",
      name: "transhipPort1Id",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      orderBy: "p.name",
      foreignTable: "name,tblPort",
      isEdit: true,
    },
    {
      label: "Transhipment Port 2",
      name: "transhipPort2Id",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      orderBy: "p.name",
      foreignTable: "name,tblPort",
      isEdit: true,
    },
    {
      label: "Transhipment Port 3",
      name: "transhipPort3Id",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      orderBy: "p.name",
      foreignTable: "name,tblPort",
      isEdit: true,
    },
    {
      label: "Port of Unloading",
      name: "",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      orderBy: "p.name",
      foreignTable: "name,tblPort",
      isEdit: true,
    },
    {
      label: "Port of Destination",
      name: "fpdId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      orderBy: "p.name",
      foreignTable: "name,tblPort",
      isEdit: true,
      required: true,
    },
    {
      label: "Nominated Area",
      name: "nominatedAreaId",
      type: "dropdown",
      tableName: "tblPort p",
      displayColumn: "p.name",
      joins: "LEFT JOIN tblMasterData m ON m.id = p.portTypeId",
      searchColumn: "p.name",
      orderBy: "p.name",
      foreignTable: "name,tblPort",
      isEdit: true,
      required: true
    },
    {
      label: "Direct Port Delivery",
      name: "dpdId",
      type: "dropdown",
      tableName: "tblPort t",
      displayColumn: "t.name",
      joins: "JOIN tblMasterData m ON m.id = t.portTypeId",
      where: "m.masterListName = 'tblPortType' AND m.code = 'DPD'",
      orderBy: "t.name",
      foreignTable: "name,tblPort",
      isEdit: true,
      required: true
    },
    {
      label: "Cargo Movement",
      name: "movementTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "ISNULL(m.code,'') + ' - ' + ISNULL(m.name,'')",
      where: "m.masterListName = 'tblMovementType'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true
    },
    {
      label: "Post Carriage",
      name: "postCarriageId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblMode'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true
    },
    {
      label: "Movement Carrier",
      name: "movementCarrierId",
      type: "dropdown",
      tableName: "tblCarrierPort t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCarrierPort",
      isEdit: true
    },
    {
      label: "Transit Bond No",
      name: "transitBondNo",
      isEdit: true,
    },
    {
      label: "Carrier Code",
      name: "carrierCode",
      isEdit: true,
    }
  ],
  hblBottomFields: [
    {
      label: "Nature of Cargo",
      name: "natureOfCargoId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblTypeOfShipment'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
      required: true
    },
    // {
    //   label: "Item Type",
    //   name: "itemTypeId",
    //   type: "dropdown",
    //   labelType: "name,tblItemType",
    //   foreignTable: "name,tblMasterData",
    //   isEdit: true,
    // },
    {
      label: "MLO Code",
      name: "mloId",
      type: "dropdown",
      isEdit: true,
    },
    {
      label: "Cargo Gross Wt(Kgs)",
      name: "grossWt",
      type: "number",
      required: true,
      isEdit: true,
    },

    {
      label: "Gross Wt(Kgs)",
      name: "netWt",
      type: "number",
      required: true,
      isEdit: true,
    },
    {
      label: "Package Type",
      name: "packageId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblPackage'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      required: true,
      isEdit: true
    },
    {
      label: "No of Package",
      name: "noOfPackages",
      type: "number",
      isEdit: true,
      required: true,
    },
    {
      label: "UNO/IMO Code",
      name: "imoId",
      type: "dropdown",
      tableName: "tblImo m",
      displayColumn: "ISNULL(m.unNo,'') + ' - ' + ISNULL(m.class,'')",
      searchColumn: "m.unNo, m.class",
      orderBy: "m.unNo, m.class",
      isEdit: true
    },
    {
      label: "Invoice Value",
      name: "invoiceNo",
      isEdit: true,
    },
    {
      label: "Currency",
      name: "demurrageCurrencyId",
      type: "dropdown",
      tableName: "tblMasterData m",
      foreignTable: "name,tblMasterData",
      displayColumn: "m.code",
      where: "m.masterListName = 'tblCurrency'",
      isEdit: true,
    },
    {
      label: "Marks & Numbers",
      name: "marksNos",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
      required: true,
    },
    {
      label: "Good & Description",
      name: "goodsDesc",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
      required: true,
    },
  ],
  transitFields: [
    {
      label: "Transit Bond No",
      name: "transitBondNo",
      isEdit: true,
    },
    {
      label: "Carrier Code",
      name: "carrierCode",
      isEdit: true,
    },
  ],
  consignorFields: [
    {
      label: "Name",
      name: "shipperText",
      required: true,
      isEdit: true,
    },
    {
      label: "Type",
      name: "shipperTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblIdentificationType'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true
    },
    {
      label: "Code",
      name: "shipperIdNo",
      isEdit: true,
    },
    {
      label: "Country",
      name: "shipperCountry",
      type: "dropdown",
      tableName: "tblCountry t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCountry",
      required: true,
      isEdit: true
    },
    {
      label: "State",
      name: "shipperState",
      type: "dropdown",
      tableName: "tblState t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblState",
      isEdit: true
    },
    {
      label: "City",
      name: "shipperCity",
      type: "dropdown",
      tableName: "tblCity t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCity",
      selectedConditions: [{ "shipperCountry": "countryId" }, { "shipperState": "stateId" }],
      required: true,
      isEdit: true
    },
    {
      label: "Post Code",
      name: "consignorPostCode",
      isEdit: true,
    },
    {
      label: "Address",
      name: "shipperAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      required: true,
      isEdit: true,
    },
  ],
  consigneeFields: [
    {
      label: "Name",
      name: "consigneeText",
      isEdit: true,
      required: true,
    },
    {
      label: "Type",
      name: "consigneeTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblIdentificationType'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true
    },
    { label: "Code", name: "consigneeIdNo", isEdit: true },
    {
      label: "Country",
      name: "consigneeCountry",
      type: "dropdown",
      tableName: "tblCountry t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCountry",
      isEdit: true,
      required: true
    },
    {
      label: "State",
      name: "consigneeState",
      type: "dropdown",
      tableName: "tblState t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblState",
      isEdit: true,
    },
    {
      label: "City",
      name: "consigneeCity",
      type: "dropdown",
      tableName: "tblCity t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCity",
      selectedConditions: [{ "consigneeCountry": "countryId" }, { "consigneeState": "stateId" }],
      isEdit: true,
      required: true
    },
    // { label: "GSTIN", name: "consigneeGSTIN", isEdit: true },
    // { label: "IEC", name: "consigneeIdNo", required: true, isEdit: true },
    // {
    //   label: "Email Id",
    //   name: "emailTo",
    //   required: true,
    //   isEdit: true,
    // },
    {
      label: "Post Code",
      name: "consigneePinCode",
      type: "number",
      isEdit: true,
    },
    {
      label: "Email Id",
      name: "emailTo",
      isEdit: true,
    },
    {
      label: "Address",
      name: "consigneeAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
      required: true,
    },
  ],
  notifyFields: [
    {
      label: "Name",
      name: "notifyPartyText",
      isEdit: true,
      required: true,
    },
    { label: "PAN Number", name: "notifyParty1IdNo", isEdit: true },
    {
      label: "Country",
      name: "notifyingParty1Country",
      type: "dropdown",
      tableName: "tblCountry t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCountry",
      isEdit: true,
      required: true
    },
    {
      label: "State",
      name: "notifyParty1State",
      type: "dropdown",
      tableName: "tblState t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblState",
      isEdit: true,
    },
    {
      label: "City",
      name: "notifyParty1City",
      type: "dropdown",
      tableName: "tblCity t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblCity",
      selectedConditions: [{ "notifyingParty1Country": "countryId" }, { "notifyParty1State": "stateId" }],
      isEdit: true,
      required: true
    },
    {
      label: "Post Code",
      name: "notifyParty1PinCode",
      type: "number",
      isEdit: true,
    },
    {
      label: "Email Id",
      name: "emailCC",
      isEdit: true,
    },
    {
      label: "Address",
      name: "notifyPartyAddress",
      type: "textarea",
      rows: 2,
      gridColumn: "col-span-2 row-span-1 ",
      isEdit: true,
      required: true,
    },

  ],
  tgBondDetails: [
    {
      label: "TG Carrier",
      name: "tgCarrierId",
      type: "dropdown",
      isEdit: true,
    },
    {
      label: "TG Bond No",
      name: "tgBondNo",
      isEdit: true,
    },
    {
      label: "TG Carrier Code",
      name: "tgCarrierCode",
      isEdit: true,
    }
  ],
  tblBlContainer: [
    {
      label: "CONTAINER NO",
      name: "containerNo",
      isEdit: true,
      required: true,
    },
    {
      label: "Size",
      name: "sizeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblSize'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true
    },
    {
      label: "Type",
      name: "typeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblType'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true
    },
    { label: "ISO Code", name: "isoCode", isEdit: true, required: true },
    {
      label: "Seal Type",
      name: "sealTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblSealType'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true
    },
    { label: "Seal No.", name: "agentSealNo", isEdit: true },
    {
      label: "SOC Flag",
      name: "soc",
      isEdit: true,
      type: "checkbox",
      required: true,
    },
    // {
    //   label: "Container Agent Code",
    //   name: "Agent",
    //   isEdit: true,
    //   required: true,
    // },

    {
      label: "Cargo Gross Wt(Kgs)",
      name: "grosswt",
      type: "number",
      isEdit: true,
      required: true,
    },

    // {
    //   label: "Cargo net Wt(Kgs)",
    //   name: "netwt",
    //   type: "number",
    //   isEdit: true,
    //   required: true,
    // },
    { label: "Weight(Kgs)", name: "grossWt", type: "number", isEdit: true },
    { label: "Volume(CBM)", name: "volume", isEdit: true, required: true },
    {
      label: "NO of Package",
      name: "noOfPackages",
      type: "number",
      isEdit: true,
      required: true,
    },
    {
      label: "Package Type",
      name: "packageId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblPackage'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      required: true,
      isEdit: true
    },
    {
      label: "IMO Code",
      name: "imoId",
      type: "dropdown",
      tableName: "tblImo m",
      displayColumn: "ISNULL(m.unNo,'') + ' - ' + ISNULL(m.class,'')",
      searchColumn: "m.unNo, m.class",
      orderBy: "m.unNo, m.class",
      isEdit: true
    },
    {
      label: "Reefer Temp",
      name: "refTemp",
      type: "number",
      isEdit: true,
    },
    {
      label: "Reefer Temp Unit",
      name: "refTempUnitId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.groupId in (select id from tblMasterData where name = 'TEMPERATURE')",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },

    {
      label: "OGG Front",
      name: "oogFront",
      isEdit: true,
    },
    {
      label: "OGG Back",
      name: "oogBack",
      isEdit: true,
    },
    {
      label: "OGG Front",
      name: "oogFront",
      isEdit: true,
    },
    {
      label: "OGG Back Left",
      name: "oogBackLeft",
      isEdit: true,
    },
    {
      label: "OGG Right",
      name: "oogRight",
      isEdit: true,
    },
    {
      label: "OGG Top",
      name: "oogTop",
      isEdit: true,
    },
    {
      label: "Dimensions",
      name: "dimensionUnitId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.groupId in (select id from tblMasterData where name = 'LENGTH')",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true,
    },
  ],
  tblBlPackingList: [
    { label: "HS No", name: "hsnCode", isEdit: true },
    { label: "Cargo Item Description", name: "commodity", isEdit: true },
    // {
    //   label: "UNO Code",
    //   name: "imoId",
    //   type: "dropdown",
    //   labelType: "uno",
    //   isEdit: true,
    // },
    {
      label: "No of Packages",
      name: "noOfPackages",
      type: "number",
      isEdit: true,
    },
    {
      label: "Package Type",
      name: "packageId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblPackage'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      required: true,
      isEdit: true
    },
  ],
  attachmentFields: [
    {
      name: "attachment",
      type: "fileupload",
      isEdit: true,
      dragDrop: true,
    },
  ],
};

export const totalFieldData = {
  totalFields: [
    { label: "Total Gross Wt(Kgs)", name: "grossWt" },
    { label: "Total No of Packages", name: "packages" },
  ],
};

export const mapping = {
  notifyPartyText: "consigneeText",
  notifyFieldsCode: "consigneeCode",
  notifyPartyTypeId: "consigneeTypeId",
  notifyingPartyCountry: "consigneeCountry",
  notifyPartyState: "consigneeState",
  notifyPartyCity: "consigneeCity",
  notifyPartyPinCode: "consigneePinCode",
  notifyPartyAddress: "consigneeAddress",
};

export const advanceSearchFields = {
  bl: [
    {
      label: "Location(POD)",
      name: "podId",
      type: "dropdown",
      tableName: "tblPort t",
      displayColumn: "t.name",
      orderBy: "t.name",
      foreignTable: "name,tblPort",
      isEdit: true
    },
    {
      label: "Vessel-Voyage No.",
      name: "vesselVoyageNo",
      type: "dropdown",
      tableName: "tblVoyage v",
      displayColumn: "ISNULL(ve.name,'') + ' - ' + ISNULL(v.voyageNo,'')",
      joins: "JOIN tblVessel ve ON ve.id = v.vesselId",
      orderBy: "ve.name, v.voyageNo",
      foreignTable: "voyageNo,tblVoyage",
      isEdit: true
    },
    {
      label: "MBL No",
      name: "mblNo",
      isEdit: true,
    },
    {
      label: "HBL No",
      name: "hblNo",
      isEdit: true,
    },

    {
      label: "From Date",
      name: "fromDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "To Date",
      name: "toDate",
      type: "date",
      isEdit: true,
    },
    {
      label: "Status",
      name: "statusId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblContainerStatus'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true
    },
    {
      label: "Type of Cargo",
      name: "cargoTypeId",
      type: "dropdown",
      tableName: "tblMasterData m",
      displayColumn: "m.name",
      where: "m.masterListName = 'tblServiceType'",
      orderBy: "m.name",
      foreignTable: "name,tblMasterData",
      isEdit: true
    },
  ],
};

export const gridButtons = [
  {
    text: "Add Row",
    icon: <AddIcon />,
    func: "gridAddHandler",
  },
  {
    text: "Delete Row",
    icon: <CloseIcon />,
    func: "gridDeleteHandler",
  },
  {
    text: "Copy Row",
    icon: <FileCopyIcon />,
    func: "gridCopyHandler",
  },
  {
    text: "Import Excel",
    icon: <UploadFileIcon />,
    func: "excelUpload",
  },
];
