export const listData = [
  {
    jobNo: "testing",
    jobDate: "11/07/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "COLOMBO, SRI LANKA",
    fpd: "COLOMBO, SRI LANKA",
  },
  {
    jobNo: "testing",
    jobDate: "08/07/2025",
    shipper: null,
    consignee: null,
    plr: "ICD SONEPAT DICT",
    pol: "MUNDRA PORT IN INDIA",
    pod: "NINGBO",
    fpd: "NINGBO",
  },
  {
    jobNo: "testing",
    jobDate: "08/07/2025",
    shipper: null,
    consignee: null,
    plr: "ICD SONEPAT DICT",
    pol: "MUNDRA PORT IN INDIA",
    pod: "ADEN",
    fpd: "ADEN",
  },
  {
    jobNo: "testing",
    jobDate: "23/06/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "HAMAD",
    fpd: "HAMAD",
  },
  {
    jobNo: "testing",
    jobDate: "23/06/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "HAMAD",
    fpd: "HAMAD",
  },
  {
    jobNo: "testing",
    jobDate: "23/06/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "SOHAR, OMAN",
    fpd: "SOHAR, OMAN",
  },
  {
    jobNo: "testing",
    jobDate: "17/06/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "PORT KLANG",
    fpd: "PORT KLANG",
  },
  {
    jobNo: "testing",
    jobDate: "13/06/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "JEBEL ALI",
    fpd: "JEBEL ALI",
  },
  {
    jobNo: "testing",
    jobDate: "02/06/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "COLOMBO",
    fpd: "COLOMBO",
  },
  {
    jobNo: "testing",
    jobDate: "27/05/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "JEBEL ALI",
    fpd: "JEBEL ALI",
  },
  {
    jobNo: "testing",
    jobDate: "26/05/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "COLOMBO, SRI LANKA",
    fpd: "COLOMBO, SRI LANKA",
  },
  {
    jobNo: "testing",
    jobDate: "26/05/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "JEBEL ALI",
    fpd: "KUWAIT",
  },
  {
    jobNo: "testing",
    jobDate: "26/05/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "SOHAR, OMAN",
    fpd: "SOHAR, OMAN",
  },
  {
    jobNo: "testing",
    jobDate: "25/05/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "SINGAPORE",
    fpd: "SINGAPORE",
  },
  {
    jobNo: "testing",
    jobDate: "23/05/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "LAEM CHABANG",
    fpd: "LAEM CHABANG",
  },
  {
    jobNo: "testing",
    jobDate: "22/05/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "JEBEL ALI",
    fpd: "JEBEL ALI",
  },
  {
    jobNo: "testing",
    jobDate: "17/05/2025",
    shipper: null,
    consignee: null,
    plr: "NHAVA SHEVA",
    pol: "NHAVA SHEVA",
    pod: "PORT KLANG",
    fpd: "PORT KLANG",
  },
];
